### ISSUE TITLE
Date range for Monday to Friday or 'business dates' 

### ISSUE THREAD

**Issue by arsalankhalid** [720kb/angular-datepicker#102]
Make the calendar only contain dates from Monday-Friday that are selectable.

**Comment by 45kb** [comment]
@arsalankhalid Hi, sorry, can you elaborate more what you trying to achieve, is this a feature request ?

Thank you.

**Comment by 45kb** [comment]
Going to close for the moment, feel free to re-open and explain us what's your idea.

thank you.
