### ISSUE TITLE
ng repeat performance issue

### ISSUE THREAD

**Issue by basith374** [720kb/angular-datepicker#104]
I would like to report a performance issue due  to the repeated use of datepickers inside ng-repeat. The complete webpage and every other functions has become slow due to this.Is there any way to speed it up ?

**Comment by jonathanobino** [comment]
I was going to report the same thing, too many watchers!
One solution can be to use one time binding introduced in angular 1.3 to fix some performance issue and to reduce some watchers 
http://toddmotto.com/angular-one-time-binding-syntax/

**Comment by 45kb** [comment]
Hi i refer to https://github.com/720kb/angular-datepicker/issues/25

**Comment by 45kb** [comment]
Actually, yes, is slow, we are trying to keep time to refactor the code.
