### ISSUE TITLE
Allow re-focus after date selection

### ISSUE THREAD

**Issue by bwilson-ux** [720kb/angular-datepicker#105]
Hi there - big fan of this date picker, wondering how easy it would be to allow a setting to allow the input to "re-focus" after date selection. The reason being is when using the date picker as an integral part in large to medium sized forms, it would allow the user to continue to tab through the remaining fields without having to re-click in the next selection. Hope this makes sense! It would certainly be a major plus for using the datepicker in forms overall. Cheers!

**Comment by 45kb** [comment]
Hi have a look here: https://github.com/720kb/angular-datepicker#re-focus-input-after-selecting-date

:+1:

**Comment by bwilson-ux** [comment]
You absolute hero! :clap: :clap: :clap: Thanks a million :+1:

**Comment by 45kb** [comment]
:+1:
