### ISSUE TITLE
Datepicker should be appended to body

### ISSUE THREAD

**Issue by MiguelMike** [720kb/angular-datepicker#107]
Datepicker in an area with `overflow:none` can be obstructed. It could be fixed using tether or something similar, but doesn't seem possible right now.

**Comment by 45kb** [comment]
Hi, thanks for the tip! 
The library is written to not use any external dependency.

Actually you can edit the CSS https://github.com/720kb/angular-datepicker/blob/master/src/css/angular-datepicker.css and also you could bind a new directive to achieve what you want somenthing like: ```<datepicker to-body></datepicker>```

It's just all it comes to my mind at the moment.

**Comment by MiguelMike** [comment]
Ok, I understand that avoiding dependencies might be a priority. This is good. But the inability to display the datepicker not limited by the container holding the input is a major flaw.

Well, anyway. I'll try to solve it using one of the ways you mentioned.

**Comment by 45kb** [comment]
@MiguelMike i agree, just try by CSS should be ok :)

If you get it work i would love to check it, cause actually i don't have any clue about this other trying by CSS indeed

**Comment by MiguelMike** [comment]
I'll get back to you when I get it working.

**Comment by 45kb** [comment]
Thank a lot :+1:

**Comment by viveleroi** [comment]
I'm seconding this, the overflow of an ancestral element prevents us from using this as-is. I haven't looked at your source but it's primarily a matter of compiling the dialog and appending to the body. `ui-bootstrap` does it but they have a completely different fatal flaw.

**Comment by 45kb** [comment]
Now it's possible, check the latest version https://github.com/720kb/angular-datepicker/releases/tag/0.2.17-beta

datepicker-append-to=""

it could be an '#id' or a '.classname' or simply 'body'
