### ISSUE TITLE
Can't type in a date

### ISSUE THREAD

**Issue by holtjonathan** [720kb/angular-datepicker#111]
Some of my users love the ability to pick a date but some prefer to still type it in.  Whenever I use this datepicker, the calendar that is displayed is put on top of my input box.  This prevents the user from manually typing it in.

I see in your example that this doesn't happen.  Is there a setting that I must specify so this calendar doesn't appear over my input box?

**Comment by holtjonathan** [comment]
Well this library seems REALLY well supported...

**Comment by 45kb** [comment]
Hi @holtjonathan  sorry for the delay, we are concentrating all our strength to write a new version of the the modules, anyway, i do not understand the part "the calendar is put on top of my input box" do you have any screenshot or code example to check it?

There is no option for what you are asking, but trying here i can type the value in the input http://720kb.github.io/angular-datepicker/, doesn't work for you?

**Comment by holtjonathan** [comment]
Hey @45kb.  Here is a screenshot of the issue that I am facing.
![datepicker](https://cloud.githubusercontent.com/assets/1995569/11097799/3b0df7fe-886f-11e5-83d6-58394d010337.png)

When the user enters the textbox, the datepicker is displayed on top of the textbox.  This prevents users from typing in their data.

**Comment by holtjonathan** [comment]
In the example that you provided...the datepicker is displayed under the textbox, thus allowing me to enter a date.

**Comment by 45kb** [comment]
Hi, ok, but this is not the normal datepicker behavior, did you edited the original CSS file?

**Comment by holtjonathan** [comment]
I changed the color (I picked the green you see in the SS) but other than that, no I did not touch it.

**Comment by 45kb** [comment]
mmm ok, looks like you broke something there, however, try adding:

```._720kb-datepicker-calendar{ margin-top:50px}```
or 
```._720kb-datepicker-calendar {margin-bottom:-50px;}```

Should fix it, let me now please :)

**Comment by holtjonathan** [comment]
That did it!  Although I didn't touch this setting before ;-)

Thanks man

**Comment by 45kb** [comment]
No problems, you're welcome!

**Comment by holtjonathan** [comment]
Follow up question/issue, if I type in `11-03-2015` as my date and then open the calendar, it doesn't show that date as being selected.  I have to actually click it from the datepicker.  Is this normal behavior?  Even the example that you posted seems to do this.

**Comment by 45kb** [comment]
Yes there is no typing binding on the datepicker

**Comment by holtjonathan** [comment]
Any interest in that changing in the future?

**Comment by 45kb** [comment]
Could be great to have it yes, as an option of course  something like ```date-typer="true|false"```

**Comment by holtjonathan** [comment]
Yea, I think it would add a lot to the usability of this library.  This lib is already good and this could make it great :)

**Comment by 45kb** [comment]
@holtjonathan Just released the option `date-typer=""` use it like this `date-typer="true"` and if you can let know if any problem.

Thank you

**Comment by bwilson-ux** [comment]
Sorry to hi-jack this issue but I have been playing around with this new feature (which is a great addition) and have added a little snippet in to allow the user to hit `tab` and refocus onto the input allowing them to tab again to format the date and move onto other inputs in the form.

`

                    if ($scope.dateTyper === 'true') {

                        thisInput.on('keyup blur', function onTyping(event) {

                            if (event.which === 0 && angular.element(theCalendar).hasClass('_720kb-datepicker-open')) {
                                setInputValue();
                                thisInput[0].focus();
                                $scope.hideCalendar();
                            }
`

Ideally when you hit `tab` it would move onto the next input but I couldn't quite get that part working... 

Again, apologies for hi-jacking this issue but it seemed to fit well.

**Comment by 45kb** [comment]
Ok understood, you are actually unable to change selection via tab key, i will try something later for this

**Comment by bwilson-ux** [comment]
@45kb I see what you mean - no worries at all, was more of a nice to have but understand what you mean. The other solution I investigated was ofcourse binding the calendar to a "selector" which allows either free-typing OR date selection via the calendar pop up but I can see there is a small issue regarding that here:

https://github.com/720kb/angular-datepicker/issues/62

Again if I haven't said already, a massive fan of the datepicker and appreciate all the good work that has gone into it!

:gem:

**Comment by holtjonathan** [comment]
Sorry for my delayed response.  I haven't had time to look into the 'date-typer' just yet but I'm looking forward to it.  Thanks for the awesome support.

**Comment by holtjonathan** [comment]
To expand on @bwilson, the option to tab over all of the stuff within the date picker would be nice.

When I make forms, one of my requirements is that the user can tab thru everything.  They will not like having to press tab 20 times to get thru the datepicker.

Just my 2 cents.

**Comment by bwilson-ux** [comment]
@holtjonathan 100% agree, great support and the tabbing aspect is the final piece of the jigsaw in my eyes - either that or the suggestion of focus class being issued to allow users to click an icon to show the menu OR just type it by hand. :) Thanks again :cake:
