### ISSUE TITLE
detect edges

### ISSUE THREAD

**Issue by mcometa** [720kb/angular-datepicker#112]
Is there a way that this can detect edges so that it doesn't get clipped when it shows up?

**Comment by 45kb** [comment]
Hi @mcometa  what you mean by "clipped"? Do you have a practical example or screenshot ?

thank you.

**Comment by mcometa** [comment]
Here is a screenshot of the part where I used your module, firstly, thanks! :)

As you can see the bottom part is cut off. Is there I way that I can prevent this from happening? Like, detect that the element will off screen and some parts of it will be cut off so display it above the input box instead. I hope you get it. 

<img width="260" alt="calendar" src="https://cloud.githubusercontent.com/assets/66358/11097039/0aceb6b4-88d8-11e5-8e78-0cf1a4425938.png">

**Comment by 45kb** [comment]
@mcometa you don't have to thank me, thanks to you to report the issue.

At the moment, my best suggestion would be to make the datepicker  full page on your app or in a modal like, what you think?

Because the dirty way should be to add more bottom padding to your page, and i guess the only way.

**Comment by mcometa** [comment]
Adding some padding at the bottom is what I am thinking of to fix it. The modal, I think is a bit too shocking/obtrusive for the app.

Thanks man!

**Comment by 45kb** [comment]
@mcometa you're welcome and my last suggestion would be, add an extra directive that toggles the page bottom padding only when you focus/blur on the input :) so that you can avoid extra overflowing or anyway bottom space in your page.

For example

```<input toggle-bototm-padding />```

Really not a clean solution but i am afraid at the moment is really the only one.
