### ISSUE TITLE
i18n and angular-dynamic-locale.

### ISSUE THREAD

**Issue by padmkris123** [720kb/angular-datepicker#113]
Hi,

I am trying to integrate date-picker with angular-dynamic-locale. 

When i use tmhDynamicLocale.set('es-us'); and open date-picker, the days still appear in English (default locale). If i use the left/right arrows it changes the month to Spanish but the days still remain in English.
Has anyone tried it? Thanks.

**Comment by 45kb** [comment]
Hi, i don't know much about angular-dynamic-locale, this is how the directive generates the week days https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L591

Hope it could help, there were guys using a different locale setting and got it to work, but they were using angular-locale.js files, for example here: https://github.com/720kb/angular-datepicker/issues/36

**Comment by 45kb** [comment]
Looks working at all, if you still having issues let know below.

Thank you :+1:

**Comment by MattMattV** [comment]
I still have a similar problem using [tmhDynamicLocale](https://github.com/lgalfaso/angular-dynamic-locale)

At page load, if the user open datepicker, months and days will be nice translated.
if the user changes its locale, the datepicker will still have the previous locale.

BTW I tried to put breakpoints to see when the strings are generated and they was never triggered..

Finally I must say thanks for that directive, it perfectly do the job !
