### ISSUE TITLE
directive name

### ISSUE THREAD

**Issue by valera33** [720kb/angular-datepicker#114]
I am using https://material.angularjs.org/ and their datepicker is not suitable for me, I am truing to use this one in my application. But, I came across such error: Error: [$compile:multidir] Multiple directives [datepicker, datepicker] asking for new/isolated scope. So I had to rename your directive to "datepicker720".

**Comment by 45kb** [comment]
@valera33  hi, yes try using `<div class="datepicker">` or maybe '<div datepicker>' instead of `<datepicker>` otherwise the only way is to remove their directive to use this.

**Comment by valera33** [comment]
Thanks,
<div class="datepicker"> works perfectly fine!

**Comment by 45kb** [comment]
You're welcome :+1:
