### ISSUE TITLE
Overriding layouts

### ISSUE THREAD

**Issue by rifer** [720kb/angular-datepicker#117]
Hi,

thanks for your work, it's really a great directive. After read the documentation I've don't find any way to override the template layouts. I would like to show the years in a different way, on the footer and some complement behavior. Just writing the js I can do this, but Im not sure if I can use any external custom file wich override the default views.

Thankyou so much

**Comment by 45kb** [comment]
Hi @rifer you can fork the repo and make your changes, the html template is inside the directive, just change positions to the html  elements, etc...

Much of the changes are usually only CSS related, so i suggest just to give a look at the code :+1: 

For any further help or informations, feel free to reply here :)

**Comment by rifer** [comment]
Ok, I know it. I was just trying to set it like an option wich allow to use any external file and so not to have there the layout html or even allow the overriding of that default template.

Thanks a lot, again

**Comment by 45kb** [comment]
I agree, but as the option wasn't included from the start now it will be quite a huge work to add it.

however we are moving soon to a new module version with a huge refactor, so it will be possible in the near future :+1:

**Comment by rifer** [comment]
Great, i'll be watching ;-)

Thanks again
