### ISSUE TITLE
datepicker calendar in ng-repeat never closes if item is deleted from array

### ISSUE THREAD

**Issue by defcronyke** [720kb/angular-datepicker#119]
If at least two datepickers are loaded by ng-repeat, and then one of the items in the repeating array is deleted (removing one of the datepickers), then if you open a new datepicker calendar, it will never be able to be closed.

It's as if the onblur() action for closing the calendar no longer works. The only way to make the calendars close after all this, is to add an item to the ng-repeating array again (loading another new datepicker), and then the onblur works again, but only for this new datepicker. It still won't close any of the other calendars on the page.

To reiterate, the problem starts happening when a new datepicker is loaded by ng-repeat (by adding a new element to the repeating array), and then an item is deleted from the same array (deleting one of the datepickers). After this, none of the calendars will close ever.

EDIT: The calendars can still be closed by choosing a date, but they can't be closed by the onblur action, which is annoying.

**Comment by 45kb** [comment]
@defcronyke do you have any working example?

It's hard to replicate this scenario, i know it's boring but a fiddle could be  very helpful :+1:

**Comment by defcronyke** [comment]
I don't have time to make a public example of it, but all you have to do is display some datepickers with ng-repeat, along with functioning delete buttons for them.

**Comment by 45kb** [comment]
Hi @defcronyke  what you mean by "delete buttons"?

I have tested this but it works great:

```javascript
<div ng-controller="Ctrl">
      <datepicker ng-repeat="i in antani">
        <input type="text" placeholder="{{i}}"/>
      </datepicker>
    </div>
```

There should be no need to "delete" anything since you could use a simple css class to "hide" eventually.

**Comment by defcronyke** [comment]
I mean a button to delete the item from the array that you're ng-repeating over. There are all sorts of reasons why you might want to delete an item from the array, instead of simply hiding it.

For example, let's say you have an area on your app where you can add "notes", and each note has a date associated with it (a datepicker). So then you can click a button to add a new note, creating a new item in the array, including a new datepicker. And each note is deletable. 

This is just one example where you'd want to delete a datepicker, I'm sure there are many more reasons why you might want to.

**Comment by 45kb** [comment]
@defcronyke  Try adding a delete class to the datepicker element:

```
.deleted datepicker, .deleted [datepicker], .deleted .datepicker{
display:none;
}```
