### ISSUE TITLE
date-typer option doesn't work

### ISSUE THREAD

**Issue by LukeNZ** [720kb/angular-datepicker#120]
It's as simple as that. If you have an input and apply the `date-typer="true"` option to the datepicker, any typed updates to the input won't be reflected in the datepicker.

**Comment by 45kb** [comment]
Hi @LukeNZ could you please share your html code and explain better what you typing and if it doesn't work always or in specific cases, thank you.

**Comment by 45kb** [comment]
@LukeNZ  any news? Let know if you can even if i close the issue, cause it's seems to work now.

Thank you.
