### ISSUE TITLE
initial value does not respect date-format

### ISSUE THREAD

**Issue by nbrustein** [720kb/angular-datepicker#121]
With the following html, the date is not formatted correctly when there is an initial value of myTime.  It only gets formatted after selecting a new value.

         <datepicker
            date-format="MMM d"
         >
            <input ng-model="myTime" type="text"/>
         </datepicker>

**Comment by nbrustein** [comment]
Actually, I was wrong about the issue here.  I was trying to bind to a date object, but angular-datepicker is expecting a string.

So, this is actually a feature request.  It would be nice if it was possible to bind to a Date format rather than a string.  (So in the example above, `myTime` would be a date object)

**Comment by 45kb** [comment]
@nbrustein thank you for reporting this, yes it's a known problem, you'll always have to `Date().toString()`

Will look forward to make some sweet changes. :+1:
