### ISSUE TITLE
date-format not working properly

### ISSUE THREAD

**Issue by EkoMcCloud** [720kb/angular-datepicker#122]
If you set you date format directly in html (date-format="yyyy-MM-dd") the component works great, however, you can't bind the date-format to a scope variable.

Controller/Directive code :
```javascript
if(myCondition)
    scope.date_format="yyyy-MM-dd";
else
    scope.date_format="MM-dd-YYYY";
```

HTML :
```html
<datepicker date-format="{{ date_format }}">
    <input type="text" />
</datepicker>
```

Edit:
I just looked at the sourcecode, this can be fixed by deleting the dateFormat initialized with attr.dateFormat and adding it to the scope (like dateSet, dateMinLimit...).

**Comment by 45kb** [comment]
Hi @EkoMcCloud  from my tests it works great using a scope variable by controller, do you mean observing it for when it changes?

**Comment by EkoMcCloud** [comment]
Hi! 

Thanks for your quick reply. As a sidenote I'm working on angular 1.2 which may explain the behaviour i'm describing.

It didn't work for me when setting it from my custom directive link function. With my example the output date looked like "2 Déc 2015" (french format) despite the fact that my date_format variable was set to "yyyy-MM-dd".
The workarounds that both worked for me were :
- Editing the calendar sourcecode to set the date-format property on the scope
- Using an angular filter function in my template to make sure the format was set at the component initialization.

From what I've seen, the attribute is grabbed and stored in your link function, which is called only once at the component initialization.

**Comment by 45kb** [comment]
Hi, first be sure to use one of these formats  https://docs.angularjs.org/api/ng/filter/date i actually don't know if "yyyy-MM-dd" is a correct one, it could be the real problem.

Then, if you can, update your angular version.

If you still having problems re-open please the issue and send some code/fiddle  so that with can help much more. 

Thank you :+1:

**Comment by EkoMcCloud** [comment]
Angular version issue apparently :
http://jsfiddle.net/26gdemo9/1/

Does not work with angular 1.1.1
Works with angular 1.2.1

From my own developments it does not work with angular 1.2.22 either. 
I cannot update my angular version but I solved the issue with a workaround, hope this might help someone.

Anyway, thanks for your time and replies.

**Comment by 45kb** [comment]
Thank you for reporting it!

you're welcome :+1:

**Comment by wouldgo** [comment]
[Requirement](https://github.com/720kb/angular-datepicker#requirements) is ng 1.2+

**Comment by ganeshverma** [comment]
not working Attribute or class
