### ISSUE TITLE
Z-Index

### ISSUE THREAD

**Issue by SydneySmith** [720kb/angular-datepicker#123]
I'm having trouble getting the drop down section to overlap the section below.  I've set my Z-index to 999, but no luck.  Any recommendations?

._720kb-datepicker-calendar {
  background: white;
  border: 1px solid #d3d3d3;
  color: #333;
  position: absolute;
  z-index: 999;
  min-width: 220px;
  margin: 0 auto;
  width: 101%;
  -webkit-box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1) inset;
  -moz-box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1) inset;
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1) inset;
  visibility: hidden;
  overflow:hidden;
  margin-left:-0.5%;
  padding: 0 0 2% 0;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}

![dropdown](https://cloud.githubusercontent.com/assets/12926298/11538714/c70f4fee-98e8-11e5-9dc7-d4201a5e8629.jpg)

**Comment by 45kb** [comment]
Hi @SydneySmith  you could try with some sort of `transform:translateZ()` or it's impossible, you'll have to put the datepicker in `position:fixed` to achieve what you want.

**Comment by tucq88** [comment]
`position:fixed` works but I don't think it's a right way :(

**Comment by 45kb** [comment]
Try now the new version https://github.com/720kb/angular-datepicker/releases/tag/0.2.17-beta

datepicker-append-to

is documented here : https://github.com/720kb/angular-datepicker#doc (look at the end of the table)
