### ISSUE TITLE
date-typer and date-format

### ISSUE THREAD

**Issue by devleesch** [720kb/angular-datepicker#126]
It seems that date-typer do not use the the format specified in the date-format.

We use this HTML :

``` html
<datepicker date-format="dd/MM/yyyy" date-typer="true>
    <input ng-model="date" />
</datepicker>
```

When we type directly in the input, it seems that the date is recognize with the format "MM/dd/yyyy".

**Comment by 45kb** [comment]
Hi thanks for the suggestion, working on this here https://github.com/720kb/angular-datepicker/tree/date-typer-live-format

If you want to help feel free!

**Comment by 45kb** [comment]
Created a new branch to test this out https://github.com/720kb/angular-datepicker/tree/date-typer-live-format

The big problem is how to detect when user type a day or a month, for example `typing 08-09-2016 ` you'll not be able to understand if 08 is the month or the day number

Any idea/suggestion is appreciated.

**Comment by jkevingutierrez** [comment]
+1

**Comment by SarahJane87** [comment]
+1
