### ISSUE TITLE
Datepicker doesn't hide when an input loses focus

### ISSUE THREAD

**Issue by tomecko** [720kb/angular-datepicker#131]
Imagine there are two inputs. The first one is a datapicker and the second one is an ordinary text input. Click the first input and press TAB to focus the second input. Unfortunately a calendar doesn't hide then.

See http://plnkr.co/edit/dWoeM7?p=preview for demo.

**Comment by 45kb** [comment]
@tomecko Hi, sorry for the delay, i am unable to reproduce the problem, looking at your plnkr it looks empty!?

Can you please specify also on which browser  and browser version it happens?

At the moment i've tested both on Firefox , Safari and Chrome and seems to work fine.

Thank you.

**Comment by tomecko** [comment]
@45kb Empty, are you sure? I opened it in incognito mode and it's not empty. How come? If it's really empty for you I will try to share demo code in different way.

Tested on Chrome Version 42.0.2311.152 (64-bit) and FF Dev Edition 45. Both on Linux.

Thanks for the reply.

**Comment by 45kb** [comment]
@tomecko Ops, sorry the first time i opened the link it did load the script, now i see.

Seems like tabindex is the problem, because tabindex is used to navigate the datepicker calendar!

**Comment by tomecko** [comment]
@45kb Have you seen https://github.com/720kb/angular-datepicker/pull/132?

**Comment by 45kb** [comment]
@tomecko For sure, i am testing it, i will merge the changes, later, thank you!

**Comment by hsiri** [comment]
hi @45kb ..
what's the status of this issue? :D

**Comment by 45kb** [comment]
@hsiri  Looks closed now https://github.com/720kb/angular-datepicker/releases/tag/0.2.22-beta

Try it if you can, if still any problem report and i will check it again.

Thank you for your patience.

**Comment by hsiri** [comment]
hello @45kb. looks like the behaviour is inconsistent.
i have date picker on two pages, when i access page 1, the date picker closes. Then i access another page, the date picker does not close anymore. But when i refresh the page, the date picker then closes.

**Comment by 45kb** [comment]
@hsiri  Are you sure is not a cache problem? Can you send me the code inside a fiddle please, thank you.

**Comment by tomecko** [comment]
@45kb Well, mine changes were a little bit different I think, see
https://github.com/720kb/angular-datepicker/pull/132/files

**Comment by 45kb** [comment]
@tomecko  thank you, we pass the ball to @hsiri  :+1: 

Can you try with this file please https://github.com/tomecko/angular-datepicker/blob/00e0093c945d45fdc68ccfdd2ef8b8537d6adfc6/src/js/angular-datepicker.js

**Comment by hsiri** [comment]
i'm also thinking of the caching issue. i'm currently checking it. thanks!

**Comment by 45kb** [comment]
@hsiri Usually you can disable caching through the developer tools of the browser ;)

Let know thanks

**Comment by hsiri** [comment]
i have already disabled caching but i can still experience the calendar that does not hide when focus out

**Comment by 45kb** [comment]
In this case, could you be so gentle to tell which Browser and browser version, wich OS and if it happens on multiple browsers or only that one.

Then a fiddle could be great, actually it works great for me and i can't understand what's wrong at the moment...

**Comment by hsiri** [comment]
sorry if i sounded rude.
i'm testing it on Chrome Version 47.0.2526.73 (64-bit), OS X

I'm currently debugging on my code, maybe there's also something wrong with my code :D

**Comment by 45kb** [comment]
@hsiri  no problems, let me know as you are sure there is a bug, better if with a fiddle so that i can retry simulating the bug. :+1:

**Comment by hsiri** [comment]
yeah sure. thanks for the help
one observation of my issue above: if i click on another field<since i have an input box beside the datepicker>, the calendar closes. if i click anywhere outside the date picker except for the fields, the calendar closes. i will try to provide a fiddle later.
thanks :D

**Comment by hsiri** [comment]
this is weird, i tried adding the hiding of calendar when focusout blur, and that solved my issue. i can't replicate the issue even on fiddle @.@

**Comment by 45kb** [comment]
@hsiri Glad that you found a working solution :+1:

**Comment by hsiri** [comment]
hi @45kb can we add the hiding of calendar in focusout blur?
i actually tried to use this  https://github.com/tomecko/angular-datepicker/blob/00e0093c945d45fdc68ccfdd2ef8b8537d6adfc6/src/js/angular-datepicker.js, and this works. it turns out that the code here in focusout blur has the hiding of calendar

**Comment by AshishTiwariMEAN** [comment]
Not working. When we clicked on ICON then input filled not fillup properly. Please provide better solution for this.

**Comment by curiousalok** [comment]
sir i am still facing this issue and won't find a solution if i click inside a control then calendar hides but if i clicked anywhere else in the form the calendar is not hiding pls help...
