### ISSUE TITLE
Datepicker how to disable sunday and saturday

### ISSUE THREAD

**Issue by 16code** [720kb/angular-datepicker#133]
I want to disable the weekend.

**Comment by 45kb** [comment]
@16code Hi, sorry for some delay, at the moment this is not possible by default.

Looking forward to introduce this feature asap.

If you want to PR something you  have done, we'll be glad about it!

Thanks :+1:

**Comment by srokatonie** [comment]
Try this: https://github.com/720kb/angular-datepicker/issues/145
