### ISSUE TITLE
Timezone date-set supports 1 format

### ISSUE THREAD

**Issue by Donny5300** [720kb/angular-datepicker#134]
First of all: lovely package, i only ran into some trouble with the date-set. Date-set only handles month day year instead of d-m-y which is confusing, because the date-format can be set to day month year. In the Neterlands where i live we use d-m-Y, USA perhaps m-d-Y? Not a bug, but maybe a feature :)

**Comment by 45kb** [comment]
@Donny5300 Do you mean date-set="" + date-format="" doesn't work togheter at same time?

**Comment by 45kb** [comment]
Going to close the issue, if you can please reopen it and give us more details, we'll be in touch, thank you.

**Comment by Donny5300** [comment]
My apologies, didnt replied on your question. Ill come back at this later when i reproduced the issue

**Comment by 45kb** [comment]
Ok thanks @Donny5300  no problems.
