### ISSUE TITLE
date-set put value in input field, which in return triggers angular filters

### ISSUE THREAD

**Issue by palsingh** [720kb/angular-datepicker#135]
Hi @45kb ,
I've a date range filter which filters some data. date-set set date in input field which triggers angular filter. There should be an option which only set date in calendar, not in input field.

I made a commit for this previously, but now this functionality is been removed. I want to use latest version of date picker and also want that feature. Would you want to make another PR for this?

Commit link: https://github.com/720kb/angular-datepicker/commit/22babc9ca1df7bb70b20b88af76c98be814006ba#diff-25beb811844343dc768ce59e4b1ffaf1

**Comment by 45kb** [comment]
@palsingh Hi, yes sorry, we refactored the module and we are looking forward to refactor more, probably it got lost, sorry for that.

I will reintroduce this asap with a new module version :+1:

**Comment by 45kb** [comment]
@palsingh So i checked the README, it was named different it is "date-set-hidden="true"" !

**Comment by palsingh** [comment]
@45kb Thanks mate.

**Comment by 45kb** [comment]
@palsingh you're welcome :+1:
