### ISSUE TITLE
Allow custom classes on _720kb-datepicker-calendar element

### ISSUE THREAD

**Issue by viveleroi** [720kb/angular-datepicker#136]
It would be helpful to accept a custom class name which will be used on the calendar element itself.

When the calendar is appended to an element other than the original input, there's no longer any association (DOM-wise) of the two. You're not positioning the calendar visually under the input (which most libraries do and I'll open as a separate ticket), so if we have a right-aligned input, the calendar appears in the wrong place.

![](http://puu.sh/mvDZC/534ee62528.png)

Since there's no longer any css hierarchy available for selecting this calendar, we'd need a custom class name.

Something like `datepicker-calendar-classname="my-custom-class"`

**Comment by 45kb** [comment]
Yes, @viveleroi  this is something that could help, asap you'll have this possibility :+1:

**Comment by 45kb** [comment]
@viveleroi  shipped here: https://github.com/720kb/angular-datepicker/releases/tag/0.2.18-beta

Thank you for the suggestion.
