### ISSUE TITLE
Datepicker Orientation

### ISSUE THREAD

**Issue by jlouazel** [720kb/angular-datepicker#138]
Hi!

I'm wondering if there is any easy way to orient the datepicker. It's always on bottom of the input but I wanted to have it on top of it.

Thanks.

**Comment by 45kb** [comment]
@jlouazel Hi, of course, you can edit the css theme to your needs :+1:  OR append the datepicker where you wish using ```datepicker-append-to=""``` https://github.com/720kb/angular-datepicker#doc
