### ISSUE TITLE
Other child than input

### ISSUE THREAD

**Issue by jlouazel** [720kb/angular-datepicker#139]
Is there any way to have a child other than an input? 

I wanted to have a link which would open the calendar but I saw a direct reference to `input` in your code.

Thanks.

**Comment by 45kb** [comment]
@jlouazel  hi, please, what you mean by other child, because the input is there to collect the ngModel of the selected date.

You could hide the input inside your link for example.

**Comment by 45kb** [comment]
Hi @jlouazel  what you mean by other child, because the input is there to collect the ngModel of the selected date, you could make it invisible inside your link....
