### ISSUE TITLE
Update function

### ISSUE THREAD

**Issue by jlouazel** [720kb/angular-datepicker#140]
Hi,

It would be a great feature to be able to call a function when dates are updated. Do you plan to do that one day?

Have a nice day.

**Comment by 45kb** [comment]
@jlouazel  hi it is already possible, just watch/observe the input value or the model itself and launch your function :+1:

**Comment by jlouazel** [comment]
I would like to avoid as much as possible $watch in my code. Calling a function instead of $watch would be more efficient since the data will not change very often.

**Comment by 45kb** [comment]
@jlouazel  i understand, but look, ```<input datepicker ng-model="date"/>``` is angular way, nothing so dangerous or not efficient, is like using a common ngModel on a common input.
