### ISSUE TITLE
There should be a way to display one format and store another format in model

### ISSUE THREAD

**Issue by miqdadalik** [720kb/angular-datepicker#141]
When user select a date, I want to show them in "Jan 01, 2016" and I want to store only timestamp in my model.

Is there any way to do the same?

**Comment by 45kb** [comment]
Hi @miqdadalik  this is notp ossible through the directive itself, see https://github.com/720kb/angular-datepicker/issues/11

However you could use the angular date $filter() if you wish to modify the model or to show different formats in your page.

**Comment by miqdadalik** [comment]
Please see angularstrap datepicker
http://mgcrea.github.io/angular-strap/#/datepickers
