### ISSUE TITLE
Issue on Display of dates when using date-min-limit

### ISSUE THREAD

**Issue by hsiri** [720kb/angular-datepicker#142]
Pre-requisite: set date-min-limit to current date (example 2016/01/26
Steps on How to Replicate:
1.) On first click of the datepicker, the current month and day is the default loaded

![1](https://cloud.githubusercontent.com/assets/14919678/12585985/6541bdb6-c489-11e5-878e-5eafece06f43.png)

2.)  When I click the Previous button, you will notice the calendar changes but it is still showing January 2016. If you notice,

   - this is actually the December 2015 calendar, only it is still showing January 2016 and
   - the enabled dates are similar to the remaining January 2016 dates. 

![2](https://cloud.githubusercontent.com/assets/14919678/12586007/7122c968-c489-11e5-8882-cc6e6e38760b.png)

3.) On 2nd click of the Previous button, only then it will show December 2015 with all days disabled.

![3](https://cloud.githubusercontent.com/assets/14919678/12586019/79e01d4e-c489-11e5-82f4-5dbd18b2384c.png)

**Comment by 45kb** [comment]
@hsiri  Hi thank you for reporting this, it should be fixed in the last module version, let know if still any trouble with that

**Comment by hsiri** [comment]
Nice! but if possible, can we just disable the previous button in the calendar? So that it won't lead to confusion that it's clickable yet the calendar does not update

**Comment by 45kb** [comment]
@hsiri  This is something not simple, i will try something as soon as possible, if you have some idea or want to try something feel free to help

**Comment by hsiri** [comment]
can't we add the disable part only when there is value in date-min-limit? @45kb

**Comment by 45kb** [comment]
@hsiri Of course it is possible but what i am saying is, we need to check if next or previous month is a selectable date before you can click the button, so that's not very easy, just that :)

**Comment by hsiri** [comment]
ooops sorry @45kb 
the current update is the previous button is enabled but when i clicked it, the calendar won't update to the previous months right? provided that i set value to date-min-limit

**Comment by 45kb** [comment]
Yes

**Comment by hsiri** [comment]
hmm maybe i'm not getting it, but since we set a date-min-limit-value, isn't it that the dates before the date-min-limit won't be selectable?

**Comment by 45kb** [comment]
@hsiri Do you mean, showing dates but make them not selectable?

**Comment by hsiri** [comment]
@45kb hmmm you said that you need to check if next or previous month is a selectable date before you can click the button, but we're setting a date-min-limit value, so that means that the dates before that are not selectable. say we're setting 01/27/2016 as the minimum date, so the months before that are not selectable right? so maybe we could just disable the previous button since the past dates are not selectable. is that okay? :)

**Comment by 45kb** [comment]
@hsiri  I am thinking about it, maybe it is more convenient to be able to browse any month and just show disabled dates where not selectable, need more time for this

**Comment by hsiri** [comment]
@45kb yeah you have already implemented that but the issue above occurs.
okay we'll just be waiting for future releases. anyways thanks for your prompt response
:+1:

**Comment by 45kb** [comment]
You're welcome :+1:

**Comment by 45kb** [comment]
Try now, it should work as exepected https://github.com/720kb/angular-datepicker/releases/tag/0.2.20-beta

**Comment by hsiri** [comment]
nice :+1: 
thank you very much :+1:

**Comment by 45kb** [comment]
you're welcome, if any further trouble, please let know :+1:

**Comment by hsiri** [comment]
i'm currently testing it. i'll give another feedback later :D

**Comment by hsiri** [comment]
hmmm i think i saw something.
i set date-min-limit to 2016/02/28, the calendar would show the January dates with no previous button but there is a next button, when i clicked the next button, the February dates are shown and again with no previous button. maybe you should display at first as default the month of the value of date-min-limit :D

**Comment by 45kb** [comment]
Ok thats probably because there is no control over THIS month, will try something as soon as possible.

Thank you and if you find something more let know please :+1:

**Comment by hsiri** [comment]
yey! okay thank you so much for helping me :+1:

**Comment by 45kb** [comment]
No problems, i am fixing bugs, so glad to help everyone ;)

Try with latest version if you can:  https://github.com/720kb/angular-datepicker/releases/tag/0.2.21-beta

**Comment by hsiri** [comment]
alrights! looks good!!
nice one! thanks
:+1:  :100:

**Comment by 45kb** [comment]
Glad :+1: 
Have a nice day.

**Comment by akshay-bbytes** [comment]
i tweak the code in such a way it worked fine

$scope.minDate = moment(new Date(), 'DD-MM-YYYY').toISOString();

use moment js to convert date format.

**Comment by DwivediBhaskar** [comment]
thanks akshay-bbytes your comment help me
