### ISSUE TITLE
"date-disabled-dates" not working?

### ISSUE THREAD

**Issue by srokatonie** [720kb/angular-datepicker#144]
Hi,

I'm struggling with disabling dates. 
````
<datepicker date-disabled-dates = "{{datesDisabled}}">
    <input ng-model="deliveryDate" type="text" />
</datepicker>
````
````
var dt = new Date();
dt.setMonth(dt.getMonth() + x);	
$scope.datesDisabled.push(dt);
console.log($scope.datesDisabled);
````
Log output:
``[Date {Wed Mar 02 2016 19:36:06 GMT+0000 (GMT)}]``

"Mar 02 2016" button still active...

Maybe you have some working example?

**Comment by srokatonie** [comment]
Solution is .getTime() with 00:00:00 time:
````
$scope.datesDisabled = [];
var date = new Date();
// months oare zero indexed! +2 = 1 month ahead
var t = new Date(date.getMonth() + 2 + '/' + date.getDate() + '/' + date.getFullYear());
$scope.datesDisabled.push(t.getTime());
console.log($scope.datesDisabled);
````

**Comment by 45kb** [comment]
Hi @srokatonie  is it solved ?

**Comment by srokatonie** [comment]
Yes!

**Comment by 45kb** [comment]
thank you to show the fix!

**Comment by srokatonie** [comment]
You're welcome :)

**Comment by omarsafwany** [comment]
Tried this solution but didn't work. :/

**Comment by srokatonie** [comment]
@omarsafwany Can you show the part of your code that doesn't work?

**Comment by omarsafwany** [comment]
@srokatonie 
 
```var date = new Date();
                // months oare zero indexed! +2 = 1 month ahead
                var t = new Date(date.getMonth() + 1 + '/' + date.getDate() + '/' + date.getFullYear());
                console.log(t)
                $scope.disabledDates.push(t.getTime());
                console.log(JSON.stringify($scope.disabledDates));
```
`date-disabled-dates="{{disabledDates}}"`

When I inspect, I just get an array of dates in milliseconds but none is disabled

**Comment by srokatonie** [comment]
@omarsafwany Yes, I have an array of timestamps in my code and it works fine.

**Comment by omarsafwany** [comment]
@srokatonie could you post the exact code that's working so I can give it another try?! I tried the one above and it didn't work so I just need to make sure I am using it correctly.

**Comment by srokatonie** [comment]
I'm running Angular with Twig therefore I use different "brackets" for my variables in my template:

```
<datepicker 
	date-format = "EEEE, d MMMM yyyy"
	date-max-limit = "{[{dateMaxLimit.toString()}]}"
	date-min-limit = "{[{dateMinLimit.toString()}]}"
	date-disabled-dates = "{[{datesDisabled}]}"
	date-set="{[{dateMinDay.toString()}]}"
	>
	<input class="form-control" 
			ng-model="order.deliveryDate" 
			placeholder="Select date"
			readonly>
</datepicker>
```
JS:
```
// Datepicker disable weekends
var disableDays = function(minDate, maxDate) {
    var startDate = minDate;
    // '31' is the maximum days in a month, we want not less 
    var endDate = new Date(startDate.getTime() + monthsAhead*31*24*60*60*1000);
    var days = [];

    for (var iDate = new Date(startDate); iDate < endDate; iDate.setDate(iDate.getDate() + 1)) {
      	// months are zero indexed so + 1
      	var date = new Date((iDate.getMonth() + 1) + '/' + iDate.getDate() + '/' + iDate.getFullYear());
        
        // Disable weekend
        if ((iDate.getDay() == 0) || (iDate.getDay() == 6)) {
        	days.push(date.getTime());
        }

        // Disable day from 'disabled_days'
        if (disabled_days.indexOf(date.toString()) != -1) {
        	days.push(date.getTime());
        } 
    }
    return days;
}

// Apply disabled days
$scope.datesDisabled = disableDays(minD, maxD);
```

I just noticed that variables maxDate and maxD are not used... Hope that helps anyway

**Comment by Markus357** [comment]
Having the same issue with updating disabled dates.

Works fine if I hardcode an array string like in the docs, or bind to a scope property defined at start up (just a string as well): $scope.restrictedDates = ['2016/04/22','2016/04/15'];

After doing an ajax request I'm updating restrictedDates, and it's odd that inspecting the code shows the date-disabled-dates attribute is updated with the new string, but the calendar doesn't update.

**Comment by srokatonie** [comment]
@Markus357

1. Is the calendar initialised before or after you fetch an array of disabled dates?
2. Are the fetched days in correct format? I was struggling with it and got the best result with timestamp..

**Comment by omarsafwany** [comment]
@srokatonie I tried the code but unfortunately it didn't work also :/

**Comment by 45kb** [comment]
Hi, yes, there is no watcher for that attribute atm, the only attribute that has a watcher is `date-set=""`

**Comment by srokatonie** [comment]
@omarsafwany Have you tried hardcoding the array of the dates to be disabled?

**Comment by omarsafwany** [comment]
@srokatonie yes and this also does not work

**Comment by srokatonie** [comment]
@omarsafwany 
I'll try later to make a basic working example for that.

**Comment by srokatonie** [comment]
@omarsafwany 
[JSFiddle working example with hardcoded dates](https://jsfiddle.net/srokatonie/sb4Lwkmn/)
@45kb 
Strangely enough, it won't work with angular 1.4.8, but maybe it's JSFiddle?

**Comment by omarsafwany** [comment]
@srokatonie datepicker not working in the example

**Comment by srokatonie** [comment]
@omarsafwany try pressing run and making sure there's ```angular-datepicker.min.js``` in External resources. Also change javascript to Angular 1.21

**Comment by omarsafwany** [comment]
@srokatonie still nothing works. I tried to hardcode the dates in my app in the same way and they appear when I inspect the datepicker but none is disabled

**Comment by 45kb** [comment]
Looks like jsfiddle doesn't allow external resources from github.com, try adding the module from another link (just had a quick look)

**Comment by srokatonie** [comment]
@45kb It also works with source from github (however it's not recommended). I think @omarsafwany might have a issue in his code somewhere - maybe a typo.

**Comment by Markus357** [comment]
In my case the datepicker has a container that stays hidden until a certain option is selected in a form. When that option is picked, it grabs unavailable dates and updates the scope.

Since the datepicker is hidden, I could easily defer initializing the picker until the unavalable dates are returned. Is there a simple way of doing this?

Thanks!

**Comment by Markus357** [comment]
Managed to get the desired result by creating a custom directive with the datepicker element as the template:

```javascript
.directive('datepicker', function () {
  return {
    template: '<div class="datepicker" date-format="yyyy-MM-dd"' +
                'date-min-limit="{{ minDate }}"' +
                'date-max-limit="{{ maxDate }}"' +
                'date-disabled-dates="{{ restrictedDates }}">' +
                '<input type="text" ng-change="preferredDateChange()" ' +
                'ng-model="orderData.scheduling.preferred_date" ' +
                'placeholder="Select a date" />' +
              '</div class="datepicker">',
    restrict: 'E'
  };
});
```

Used in the main app controller as:
```javascript
$scope.add = function(ev, attrs) {
    var dtpicker = angular.element(document.createElement('datepicker')),
          el = $compile( dtpicker )( $scope );
    $("#preferred-date-label").append(dtpicker);
};
```
