### ISSUE TITLE
How to set a default date in calendar when input field is empty?

### ISSUE THREAD

**Issue by minimaldesign** [720kb/angular-datepicker#151]
Is it possible to set a default date in the calendar view when the input field is empty?

**Comment by 45kb** [comment]
Hi @minimaldesign  yes you can, check the first attribute in the [documentation](https://github.com/720kb/angular-datepicker#doc)

For example:
`date-set="2016/05/07"`

If any doubt or problem feel free to ask then.

**Comment by minimaldesign** [comment]
Apologies. I guess I didn't explain well...

What I'm trying to do is set the calendar to today - 20 years when the input field is empty (so date-set would be undefined). The idea is to make it convenient for users to set their birthday so they don't have to navigate 20+ years in the past and instead just fine tune a sensible default.

**Comment by 45kb** [comment]
@minimaldesign If i understood well, you should first set a min and max date limit like this:

`date-min-limit="{{20YearsAgoTodayDate}}"` `date-max-limit="{{todayDate}}"`

 then `date-set="{{20YearsAgoTodayDate}}"`

Let me know, however, usually, a datepicker is not really convenient for users when it comes to select a birth date, just my two cents ;)

**Comment by winstonkan** [comment]
i try to set the input field using ng-model={{active_from}} its working

but i try to set the calendar using date-set={{active_from}} its not working

ps:{{active_from}} is a string. 

why like that? thx.

**Comment by winstonkan** [comment]
the string value is "03/03/2016"

**Comment by 45kb** [comment]
@winstonkan Can you paste some of your code or even better, create a fiddle or a plunkr ?
It should works both the ways, if you see that it works using `ng-model=""` use that, no?

**Comment by winstonkan** [comment]
@45kb Thx for your reply. I already solved my problem  :) :+1:

**Comment by 45kb** [comment]
@winstonkan great :+1:
