### ISSUE TITLE
How does Append-to works?

### ISSUE THREAD

**Issue by hmaesta** [720kb/angular-datepicker#154]
I am trying to append the `datepicker` in another `div`, but I have no success.

In the example below, the `datepicker` should apper on `.test`, but it does not.
http://plnkr.co/edit/jgbQMtHuVkyfJ8EEHgoJ

**Comment by 45kb** [comment]
Hi @hmaesta please be always sure to use latest version of the module :+1: 
http://plnkr.co/edit/3GoKMBWJ3O0o0KgfyfEI?p=preview
