### ISSUE TITLE
Not highlighting any date that lands on a sunday when typing date and date-typer is on

### ISSUE THREAD

**Issue by DevEarley** [720kb/angular-datepicker#164]
I found where the issue is happening. 
Line 550 
`if (date.getFullYear() &&
                   date.getDay() &&
                   !isNaN(date.getMonth()) &&`

It should be 
`if (date.getFullYear() &&
                   !isNaN(date.getDay()) &&
                   !isNaN(date.getMonth()) &&`

Because date.getDay() is 0 on a Sunday.

**Comment by 45kb** [comment]
@DevEarley thanks!  you can easily update the module now https://github.com/720kb/angular-datepicker/releases/tag/0.2.27-beta

If any further problem, just let know :+1:
