### ISSUE TITLE
Default selected date when (date-min-limit="today" + date-max-limit="today + 1year")

### ISSUE THREAD

**Issue by johnsintal** [720kb/angular-datepicker#167]
Hi,

Great library!

`<datepicker date-format="MMM d, yyyy" date-min-limit="{{ minDate }}" date-max-limit="{{ maxDate }}" date-typer="true">
        <input class="form-input-text size-sm" name="start_state" ng-model="someModel" placeholder="some place holder" type="text" required readonly/>
      </datepicker>`

minDate = { current date }
maxDate = { current date + 1 year }

I was wondering why the date picker preselects the latest year (2016 ==> 2017) preselected?

**Comment by jackdh** [comment]
What are you expecting it to be selected to? In my experience it will preselect to the most recent date available based off of the min date.

**Comment by 45kb** [comment]
@johnsintal Hi, use `date-set=""` to set the default date

However i tried and yes that's a wrong behavior that should be fixed, thanks for reporting 👍 

@jackdh it should select the current date or anyway not a date in the future ;)

**Comment by akshay-bbytes** [comment]
i tweak the code in such a way it worked fine

$scope.minDate = moment(new Date(), 'DD-MM-YYYY').toISOString();

use moment js to convert date format.

**Comment by akshay-bbytes** [comment]
Hi, I want to disable past date, i used date-min-limit="{{ minDate }}"
$scope.minDate  =new Date().toString();
Its allowing dates from currentDate + 1 onwards,
Help me asap
Thanks for advance

**Comment by akshay-bbytes** [comment]
I tweak code which is disabling all past dates
Try this code, it worked fine for me
 ```
<datepicker date-format="dd-MM-yyyy" selector="form-control" date-min-limit="{{minDate}}">
 $scope.minDate = new Date().toDateString();
```

**Comment by 45kb** [comment]
all moved into one issue #227

**Comment by shankariyerr** [comment]
@akshay-bbytes it worked. you saved my day.

**Comment by hiteshkan123** [comment]
@akshay-bbytes Thanks It worked for me :+1:
