### ISSUE TITLE
Open calendar programmatically? 

### ISSUE THREAD

**Issue by jasperblues** [720kb/angular-datepicker#168]
Have just started angular/JS in the last few weeks, apologies for n00b question: 

How do I open the calendar programmatically?

**Comment by 45kb** [comment]
HI @jasperblues you have two options maybe more but these will work for sure:

1 - trigger a focus or click event on the datepicker input
2 - use  this CSS `._720kb-datepicker-calendar{visiblity:visible}` to your css whenever you want to show the datepicker

**Comment by jasperblues** [comment]
Thank you @45kb

**Comment by 45kb** [comment]
@jasperblues  You're welcome, looking forward to introduce a new attribute to achieve this.

**Comment by 45kb** [comment]
Actually you could use `datepicker-toggle="false"` too.

**Comment by 45kb** [comment]
Now with the new version of the module, you're welcome to try it https://github.com/720kb/angular-datepicker/releases/tag/2.1.0

**Comment by 45kb** [comment]
For anyone who will read this thread, it is now documented here: https://github.com/720kb/angular-datepicker#manually-show-and-hide-datepicker

**Comment by jasperblues** [comment]
:+1: :fireworks:
