### ISSUE TITLE
date-set not working when using date-format

### ISSUE THREAD

**Issue by pbouda** [720kb/angular-datepicker#171]
I could not really get the `date-set` attribute working, when I set certain values in `date-format` (for example "dd-MM-yyyy"). I think the transformation of the date is wrong here:

https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L348

In my case the date will be transformed to sth like '12-01-2012' and then the date cannot be parsed anymore.

When I change the line to `date = Date.parse(newValue);` then it works. How is `set-date` supposed to be used together with `date-format`? If you think my change is good I can send a PR.

**Comment by 45kb** [comment]
Can you please paste me your html because there are strange behaviors where these two attributes collide...

thanks

**Comment by pbouda** [comment]
Here is the tag and attributes I use:

    <datepicker date-set="{{ vm.dateInit | date:'dd-MM-yyyy' }}" date-format="dd-MM-yyyy">

Basically, it does not work with any format that is not supported by the JavaScript `Date` class. Instead, it would be nice if one could use any date format that the angular date filter supports, like in my example above. If the code would just use `date = Date.parse(newValue);`, then I could at least have a workaround like this:

<datepicker date-set="{{ vm.dateInit | date:'yyyy-MM-dd' }}" date-format="dd-MM-yyyy">

... so passing the `date-set` attribute a valid format for the JS `Date`, while still being able to use an angular date format for the input field.

**Comment by 45kb** [comment]
@pbouda  what `{{ vm.dateInit | date:'dd-MM-yyyy' }}` prints in the html ? However you don't have to filter again the date inside date-set usually...

Maybe i need your piece of controller if there is one so i can test it. 👍

**Comment by pbouda** [comment]
You can use `12-03-2016` instead of `{{ vm.dateInit | date:'dd-MM-yyyy' }}`, or in fact any date object or string that is not `yyyy-MM-dd` (or similar). The problem is the `date-format` here. Your code passes the value of the `date-set` to the following filter, and then to the `Date()` constructor:

    $filter('date')(new Date(newValue), attr.dateFormat)

This will be a string of the my own format. If `Date` does not recognize the format, then the date will be invalid.

**Comment by 45kb** [comment]
I don't know about your code, but here is working well https://plnkr.co/edit/1NnvdZl3y6g6l7npEJXv?p=preview

If you can make a plnkr i'll be glad to help you.

**Comment by pbouda** [comment]
It seems like the library you include in the plnkr is different to the one in master...? The plnkr version has the watch for `dateSet` in line 99, and has `date = new Date(value);` (which is OK). While in master it's here:

https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L351

With the filter.

**Comment by 45kb** [comment]
@pbouda  i included the master file you linked: https://plnkr.co/edit/GXkAO6nllL5JbLAYQOEe?p=preview

**Comment by pbouda** [comment]
The date was correct in my view, but I think I found the problem in the plnkr: if you change the date in your plunkr to `18-03-2016` it will fail. Somehow it seems the the string/date conversion is confused, like it uses the first element for months but still recovers further down the line...

**Comment by 45kb** [comment]
Oh i see... this is quite embarassing, it does not depend on the module, try in console:

`new Date('12-03-2016')`

`new Date('18-03-2016')`

Interesting, i have no idea at the moment....

**Comment by pbouda** [comment]
I think it's because Date accepts only specific strings, as standardized in IETF and ISO. It even seems to be implementation differences:

"parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies."

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

A format like "yyyy-MM-dd" will work on most implementations I guess. I think it might be an option for a workaround, but then the plugin must not use the filter with the dateFormat.

**Comment by 45kb** [comment]
@pbouda The problem is that i don't have any clue at the moment, if you try removing Date() it doesn't work at all, and date-set="" must be aligned to date-format if date-format is present, parsing without the specified format makes no sense for them to work togheter.

Do you tried anything?

**Comment by pbouda** [comment]
Yes, my workaround for now is to use `date = Date.parse(newValue);` without the filter in angular-datepicker.js and then I pass `date-set="{{ vm.dateInit | date:'yyyy-MM-dd' }}"`. Ugly, but it works. I thought about just passing a Date object to date-set, and then check the type in the plugin and only create a new Date object when it is not already one. I will try that when I find some time.

**Comment by 45kb** [comment]
So for the moment i reverted that part because you're right, the angular filter is really not doing anything and not necessary.

The problem is about ISO dates, if you try `new Date('12-03-2016').toLocaleString();`  works

So i will update the README for this.

Thanks for spotting out and if you come with some idea we'll appreciate.
