### ISSUE TITLE
datepicker-toggle not working

### ISSUE THREAD

**Issue by pbouda** [720kb/angular-datepicker#172]
I have a problem using the `datepicker-toggle` option. I use it either with a string "false" or a boolean `false`. Both do not work. I tracked down the problem to this part of the code:

https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L738

As far as I understand it will always be true, as either the comparison to the string "false" or the eval will be true. Maybe the eval is enough?

**Comment by 45kb** [comment]
Hi, yes there were a bunch of bugs, can you please try the new files so that we can release them.

JS https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js

CSS https://github.com/720kb/angular-datepicker/blob/master/src/css/angular-datepicker.css

**Comment by pbouda** [comment]
Yes, it works now with this version.

**Comment by 45kb** [comment]
@pbouda thanks a lot , see also is datepicker-show works for you if you can please. So i can release the new version 👍
