### ISSUE TITLE
datepicker-show not working correctly

### ISSUE THREAD

**Issue by pbouda** [720kb/angular-datepicker#173]
I could not get the `datepicker-show` functionality working. I had a look at the code and found that the function `checkAndToggleVisibility()` does not return anything, but is called to get a return value to set the class `_720kb-datepicker-forced-to-open` in the template:

https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L270

When I add a `return $scope.$eval($scope.datepickerShow);` at the end of the function it works fine. Is that a correct solution?

**Comment by 45kb** [comment]
Hi, yes there were a bunch of bugs, can you please try the new files so that we can release them.

JS https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js

CSS https://github.com/720kb/angular-datepicker/blob/master/src/css/angular-datepicker.css

**Comment by pbouda** [comment]
Yes, this one works with the new version.

**Comment by 45kb** [comment]
Thank you :

**Comment by sarates** [comment]
this bug reproduced on 2.1.4 version..

**Comment by 45kb** [comment]
@sarates can you please paste your code or what you trying to achieve, because i tested it again and looks ok with the last 2.1.4 version

thanks

**Comment by sarates** [comment]
When i insert datepicker intro directive with bootstrap-ui popover, datepicker is not visible (without datepicker-forced-to-open class, but checkVisibility method return true). And i use datepicker-show="true". Can you explaine how to fix this problem?

**Comment by 45kb** [comment]
@sarates As i remember, bootstrap-ui has a datepicker https://angular-ui.github.io/bootstrap/#/datepicker

Did you removed it from the bootstrap-ui? Because there will be conflicts using 2 datepicker directives...

Try using `class="datepicker"` instead of `<datepicker>` but you have to be sure to not include the bootstrap-ui datepicker directive in order to use this module...
