### ISSUE TITLE
Not updating/showing correct date when not using date-set to have a default/initial value

### ISSUE THREAD

**Issue by nixoschu** [720kb/angular-datepicker#174]
Hey there,

I just used the datepicker and it worked pretty fast and good 👍 

I just got a little problem loading / showing a default value.
In my case, I have a form which filters a set of data. This filter variables will onChange be saved into a cookie. Initially everything works fine, but when reloading the page, the value loaded from the cookie is not shown as the current date in the calendar. (ofc I bind the value to the according ng-model variable)

I build a plunkr to simulate my case

https://embed.plnkr.co/7vURQDtFrjqKGmq4cOAv/

1. select new date => date value is updated
2. open calendar => correct selected date is shown
3. reload
4. last selected date is shown 
5. open calendar => current date is shown as active

Hope you can help / advise me :)

**Comment by 45kb** [comment]
Hi @nixoschu actually there is no binding between ng-model and date setup, the only way is to save the date (like you do) and use `date-set="{{mySavedDate}}"`

Already tried this?

**Comment by nixoschu** [comment]
Hey @45kb,

yes I tried setting "date-set".
Problem is, since I don't always got a default date I need to set the "date-set" to null or undefined initially which results in "Invalid Date" which will be shown as the value in the input and further more will break the complete calendar because values are shown as "NaN".
When the page gets loaded there will be some sort of change to the input so my ng-change will be triggered which results in saving the "Invalid Date" into the cookie.

I did not set the ng-model variable as "date-set" since the tip in the readme.md said so.

I updated my plunkr with a defaultDate, maybe you can have a second look.
Thanks for any help :)

**Comment by 45kb** [comment]
@nixoschu There just were a bunch of bugs mostly typo and sintax errors, it seems to work to me:
https://plnkr.co/edit/0OSqm4A2BnlGmhIfgC4z?p=preview

Take the code and try it on your localhost, because it seems to me that plnkr doesn't allow to save cookies, here on localhost it works like a charm.

Hope this helps
