### ISSUE TITLE
Is it possible to close the datepicker view after a date was selected?

### ISSUE THREAD

**Issue by pbouda** [720kb/angular-datepicker#175]
My idea is:

* The user opens the datepicker via focus on the input element or via a button.
* The user selects a date in the datepicker via clicking on a day
* Directly after the user clicked the day the datepicker is closed and the input element is updated

I tried to find some simple way to add this to you code, but was not sure how the interaction with the "forced" open works, when `datepicker-show` is used.

**Comment by 45kb** [comment]
I guess..
You could $watch your input `ng-model` scope var and as it change you can set `datepicker-show="false"`
