### ISSUE TITLE
Datepicker modal not showing up on Mobile

### ISSUE THREAD

**Issue by trisle** [720kb/angular-datepicker#176]
It's working perfectly fine on desktop/laptop for me but for some reasons, the calendar modal wouldn't pop up on my mobile phone and tablet (iOS/safari).

``` html
<datepicker date-format="EEE, dd MMM yyyy">
	<input type="text" class="date" ng-model="event_date" placeholder="Date">
</datepicker>
```
To clarify, the input field still displays with the placeholder text, but tapping on it triggers no action at all.

Is there anything obvious that I missed?

**Comment by 45kb** [comment]
Are you sure it's not another problem maybe caused by some other code?

I am asking this because i see no problems with that...

**Comment by trisle** [comment]
Thanks for replying Fillipo :)

I have fixed this issue. For some reasons the datepicker field when in the responsive mode get layered below its container, so I added in z-index:9999 to force it to float on the surface. That fixes the problem.

Cheers!

**Comment by 45kb** [comment]
Glad for this 👍 
Have a nice day @trisle
