### ISSUE TITLE
Unable to install with bower

### ISSUE THREAD

**Issue by henev** [720kb/angular-datepicker#180]
Currently I get an error:

`ECONFLICT Unable to find suitable version for angular`

Trace:

`bower angularjs-datepicker#*    cached https://github.com/720kb/angular-datepicker.git#2.1.3
bower angularjs-datepicker#*  validate 2.1.3 against https://github.com/720kb/angular-datepicker.git#*
bower angular#~1.4.5            cached https://github.com/angular/bower-angular.git#1.4.11
bower angular#~1.4.5          validate 1.4.11 against https://github.com/angular/bower-angular.git#~1.4.5
bower angular#1.5.5             cached https://github.com/angular/bower-angular.git#1.5.5
bower angular#1.5.5           validate 1.5.5 against https://github.com/angular/bower-angular.git#1.5.5
bower angular#^1.0.8            cached https://github.com/angular/bower-angular.git#1.5.6
bower angular#^1.0.8          validate 1.5.6 against https://github.com/angular/bower-angular.git#^1.0.8
bower angular#>=1.3.0           cached https://github.com/angular/bower-angular.git#1.5.6
bower angular#>=1.3.0         validate 1.5.6 against https://github.com/angular/bower-angular.git#>=1.3.0
bower angular#*                 cached https://github.com/angular/bower-angular.git#1.5.6
bower angular#*               validate 1.5.6 against https://github.com/angular/bower-angular.git#*
bower angular#^1.3.14           cached https://github.com/angular/bower-angular.git#1.5.6
bower angular#^1.3.14         validate 1.5.6 against https://github.com/angular/bower-angular.git#^1.3.14
bower angular#>=1.4.0           cached https://github.com/angular/bower-angular.git#1.5.6
bower angular#>=1.4.0         validate 1.5.6 against https://github.com/angular/bower-angular.git#>=1.4.0
bower angular#>= 1.2.0          cached https://github.com/angular/bower-angular.git#1.5.6
bower angular#>= 1.2.0        validate 1.5.6 against https://github.com/angular/bower-angular.git#>= 1.2.0
`

My bower.json:

`"dependencies": {
    "angular": "~1.5.3",
...
},
"resolutions": {
    "angular": "1.5.3"`

My angular version is currently 1.5.5

**Comment by henev** [comment]
#181 Fixes that.

**Comment by 45kb** [comment]
Fixed, thanks for reporting, just retry now if you want.

**Comment by henev** [comment]
Works good. Thank you
