### ISSUE TITLE
Is there a way to make calendar flip automatically, if there is not enough space below?

### ISSUE THREAD

**Issue by himanshu56** [720kb/angular-datepicker#183]
`<datepicker date-format="dd/MM/yyyy">
                                             <input ng-model="start_date" type="text" placeholder="dd/MM/yyyy" required="" />
                                       </datepicker>`

**Comment by 45kb** [comment]
Hi, if you want to toggle the calendar manually, you can use:

```html
<datepicker datepicker-toggle="false" datepicker-show="{{myExpression}}"><input></datepicker>
```
