### ISSUE TITLE
Is that possible to make the calendar to select only month and year

### ISSUE THREAD

**Issue by prabhum07** [720kb/angular-datepicker#184]
Hi,

Is there any option available to show and select only month and year?

It is something like

![](https://cloud.githubusercontent.com/assets/16848610/15805274/a6290558-2b42-11e6-90e9-862d81d24c4c.png)

Thanks,

**Comment by prabhum07** [comment]
It is something like

![sample](https://cloud.githubusercontent.com/assets/16848610/15805274/a6290558-2b42-11e6-90e9-862d81d24c4c.png)

**Comment by 45kb** [comment]
@prabhum07 This could be not very easy, but you can workaround the datepicker css to show only the calendar sections you want and probably with some more hack you get what you want, obviously you can make changes inside the directive if you wish, but atm there is no specific option to achieve this.
