### ISSUE TITLE
opening on wrong month when date-min-limit is defined to another month

### ISSUE THREAD

**Issue by MatthiasDebaere** [720kb/angular-datepicker#185]
Hi,

I've created[ this plnkr ](https://plnkr.co/edit/oZWvomtKPWgl4aD5H8hl?p=preview) to demonstrate my problem. 

The problem is that when I declare a certain minimum date in the future (say 2 months from now) and I open the calendar, the month is not forwarded to the correct month (2 months from now) and still on the current month.

Is this something that can be fixed? Or is there a workaround? I've tried using date-set, which helps, but I don't want the day to be set.. I just want the calendar to open in the month corresponding with the minimum date I declared inside date-min-limit.

Thanks in advance!

**Comment by 45kb** [comment]
Hi @MatthiasDebaere 

By default, the datepicker select the today date and day.

To achieve what you want you should use also `date-set="{{minDate}}"`

**Comment by MatthiasDebaere** [comment]
Great succes! Thanks!
