### ISSUE TITLE
Can't use '-' in date-format.

### ISSUE THREAD

**Issue by MatthiasDebaere** [720kb/angular-datepicker#187]
Hello again,

It seems that I can't use the following date-format: `date-format="dd MMMM yyyy - HH:mm a"`

I've tried escaping it (`date-format="dd MMMM yyyy \- HH:mm a"`), I've tried using parentheses (`date-format="dd MMMM yyyy '-' HH:mm a"`) but it won't seem to accept it as a valid date-format :(

Screenshot:
![date-format crashes the calendar](https://i.imgur.com/o3XYhJl.png)

Is there any way to fix this or a workaround?

Thanks in advance!

**Comment by 45kb** [comment]
Hi @MatthiasDebaere  all you have to do to see if it's possible is just run it inside new Date()

Try it in console `console.log(new Date('my-date-and-time-with-my-format'));`

If it is NaN in Date() it is Nan in Datepicker too...
