### ISSUE TITLE
date-set gives invalid date in a range of dates

### ISSUE THREAD

**Issue by garaekz** [720kb/angular-datepicker#188]
When I assign the date to show in date-set it gives "invalid date" from today to the last day of June.

Example:
`<datepicker date-format="dd-MM-yyyy" date-set="13-06-2016">`

And this happens until `date-set="01-07-2016"`
Then just works fine, dunno, weird just from June 13 to 30 gives a invalid date

**Comment by 45kb** [comment]
@garaekz Can you provider please a plnkr or jsfiddle?

Remember to use a date format which is recognized by new Date() althought is not a valid date, and be sure you are setting a date format that your locale recognize, maybe you have a different locale!?

**Comment by garaekz** [comment]
http://plnkr.co/edit/6ky1BH

**Comment by 45kb** [comment]
Ok, as i said you have to set the date-set="" according to the browser locale http://plnkr.co/edit/armelA2l8Ga7khjycX17?p=preview

This works indeed, because the locale does recognise 13 as month and month number 13 doesn't exist.

Hope it is clear, if any other doubt just ask 👍
