### ISSUE TITLE
Changing Months Updates the chosen date ng-model

### ISSUE THREAD

**Issue by lpommers** [720kb/angular-datepicker#19]
If you have chosen a date, and then re-opened the picker and navigate to a different month, your previously chosen date is changed to reflect that day of whatever month you're viewing even if you have not clicked and chosen a new day.

I think it is easy to imagine a use case where someone chooses a date and then re-opens the calendar to look again, changes the month (but doesn't choose a new day), decides to keep their original date, so clicks off the calendar without making a selection. They would have unknowingly chosen a new date because changing the month automatically changes your selection.

**Comment by 45kb** [comment]
going to close it, anyway let's discuss looks interesting :)

**Comment by paddie** [comment]
This is definitely an annoyance for me as well. I don't much see a reason for anything happening that the user doesn't specifically intend. Tabbing through the months should not alter the value of the input-field, mostly it is unclear what would happen when the previous date was, say, 14, go back a month and then return to the previous month, you've effectively reset the date to 1.

This just seems like it is trying to do too many things, instead of just being a simple, non-destructive exploratory action.

Just my 5 cents, but I love the datepicker though, and I'm currently using it.

**Comment by 45kb** [comment]
@paddle hi, i think i agree with you, as soon as i can i will try something out, feel free to PR if you want, any help appreciated!

**Comment by 45kb** [comment]
@paddie  @lpommers  i just created a new branch, maybe you'll be interested in https://github.com/720kb/angular-datepicker/tree/model-change-on-click

Merging this the input model will change only by clicking on a specific day or year, so no more model changing while navigating the datepicker

**Comment by paddie** [comment]
Ahh, awesome!

—Kind regards / Venlig hilsen



    Patrick Madsen

**Comment by lpommers** [comment]
Thanks for the notification.  I'm very interested and will take a peak at
my first opportunity!

**Comment by 45kb** [comment]
You're welcome guys, i will merge it and look foward to avoid highlighted days during datepicker navigation.

**Comment by paddie** [comment]
As will I! Really appreciate you taking the time to fix this!



—Kind regards / Venlig hilsen



    Patrick Madsen

**Comment by 45kb** [comment]
Hi @paddle @lpommers  the last version should be fixing all that we discussed :) feel free to try it out and report if any problem, thank you.

https://github.com/720kb/angular-datepicker/releases/tag/0.2.3

**Comment by paddie** [comment]
When I have time to roll out internal localizations stuff into the new branch, I'll report back. We use moment.js for localizations, so if you don't mind the dependency, I can make a pull-request. 

—Kind regards / Venlig hilsen



    Patrick Madsen

**Comment by 45kb** [comment]
@paddle That will be awesome, just i am not sure cause moment.js requires a new lib to be included, can't we use angularjs ? :)
