### ISSUE TITLE
How can I target prevMonthDays without nextMonthDays using CSS?

### ISSUE THREAD

**Issue by bflopez** [720kb/angular-datepicker#193]
Both repeated elements have the classes ._720kb-datepicker-calendar-day ._720kb-datepicker-disabled and I am not sure how I can add different background colors. The HTML is generated in the JS and I do not see a template option.

**Comment by 45kb** [comment]
Hi @bflopez what are you trying to achieve ?

**Comment by 45kb** [comment]
just override the css classes you want writing your CSS after you included the main CSS file https://github.com/720kb/angular-datepicker/blob/master/src/css/angular-datepicker.css
