### ISSUE TITLE
date-format not working when init

### ISSUE THREAD

**Issue by steven274** [720kb/angular-datepicker#195]
<div class="datepicker" date-format="dd-MM-yyyy">
          <input type="text" class="form-control" ng-model="date" >
        </div>

first time input show up, it is not correct date format, after I choose date from date picker, the format will be correct

https://plnkr.co/edit/kgcuuRDh10tey2O4uuwy?p=preview

**Comment by 45kb** [comment]
Hi @steven274 

To init the date in calendar you must set it using `date-set` add this `date-set="04/07/2016"` and you'll see it works.
