### ISSUE TITLE
Make a solid date-set example that works

### ISSUE THREAD

**Issue by iezekiel** [720kb/angular-datepicker#196]
Like many others here, I cannot use your control because date-set is not working. Please make a solid example that works.

**Comment by abhishek1234321** [comment]
Is it possible to get a good example which works with `date-set`, `date-format`, `date-min-limit` and `date-max-limit` all specified at once?

**Comment by akafaneh** [comment]
Me also have an issue that date-set is not working

**Comment by winter7621** [comment]
[Here's a plunkr](https://plnkr.co/edit/1NnvdZl3y6g6l7npEJXv?p=preview) showing how `date-set` is used. Of special note, is that `date-set` is used on the `datepicker` directive and not the `input`
