### ISSUE TITLE
View doesn't reset if date not selected

### ISSUE THREAD

**Issue by nishantroy** [720kb/angular-datepicker#199]
I open the datepicker, navigate back 4 months, but I don't select a date and click out to close the datepicker. The next time I open the datepicker, it is still 4 months back and is not refocused to today.

Is there anyway to correct this behavior?

**Comment by 45kb** [comment]
Hi @nishantroy  this is the normal behavior of the datepicker, because in case you selected a date then you want to change the date selected you don't have to navigate back or forward to find the date you choosen before.

**Comment by 45kb** [comment]
You can anyway use `date-set="TODAY_DATE_HERE"` to reset it everytime on toggle.
