### ISSUE TITLE
Multiple Months

### ISSUE THREAD

**Issue by kentcdodds** [720kb/angular-datepicker#20]
jQuery UI datepicker allows you to display multiple months.I need to display two months. Is this something you could support?

**Comment by 45kb** [comment]
Can you provide an example of what you asking for?
Or anyway define better "display multiple months"?

I think i don't understand what you meant.

thank you

**Comment by kentcdodds** [comment]
Like [this](http://jqueryui.com/datepicker/#multiple-calendars).

**Comment by kentcdodds** [comment]
The use case is, our users can only select a day in the next 30 days and we want them to be able to see all 30 days without having to change months. So in most cases, that requires showing next month as well as this month.

**Comment by 45kb** [comment]
This is quite articulate, I would check later in the future, unfortunately I do not have much time, but feel free to try something out and do PR , you're welcome ;)
