### ISSUE TITLE
datepicker stop working when using ui bootstrap in the project for ngmodel pop up

### ISSUE THREAD

**Issue by mkakkar81** [720kb/angular-datepicker#200]
Datepicker was working fine until I implemented ngmodel using ui bootstrap in the project for ng model pop up. When I am running application it showing directive conflicts due to using same isolated scope. Please help me in resolving this issue.
![error](https://cloud.githubusercontent.com/assets/21203481/17903892/1a5eb89c-693b-11e6-9836-db95238bbddc.PNG)

**Comment by 45kb** [comment]
Should work using `class="datepicker"`

https://github.com/720kb/angular-datepicker/issues/116

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/issues/166
