### ISSUE TITLE
option : on change

### ISSUE THREAD

**Issue by stethewwolf** [720kb/angular-datepicker#202]
create an option that allows users to run code on date changing

**Comment by 45kb** [comment]
Yes, rootscope events are the way to go, probably the only way to go. Will try something asap

**Comment by lucas3003** [comment]
@45kb 

Would these changes work?

`'onChange': '&'` on scope definition (Currently line 862)

and

`$scope.onChange();` on the first line of setInputValue()

**Comment by 45kb** [comment]
@lucas3003 better just to `$rootScope.$emit('datepicker:date', {date: <the-date-value>})`

**Comment by lucas3003** [comment]
@45kb What about `$rootScope.$emit('datepicker:date', {date: modelDate, id: id});` on setInputValue() and `id = element[0].id` on selector?

**Comment by 45kb** [comment]
@lucas3003 this way you set id="" as mandatory, correct to set an identifier, but i could not use id="" in my html at all... :)

**Comment by lucas3003** [comment]
@45kb  Maybe ng-model could be a better identifier? (Although I have no idea how to get the name of the model)

**Comment by 45kb** [comment]
@lucas3003 actually  ng-model is the only attribute we can use as indentifier as it's always present.

But now i am a bit confused because (correct me if i'm wrong):  you should be able to watch for ng-model changes directly from your Ctrl. 

Did you tried watching the ng-model value from outside the directive?

**Comment by lucas3003** [comment]
This works:

`$scope.$watch('myDate', function(){
		console.log('Changed!');
	})`

But I think the best approach is to simply insert a ng-change directive.

**Comment by 45kb** [comment]
@lucas3003 oh right .... so it's really not needed to overdo here,  as ng-model change you can watch for it 👍  

closing, thanks :)

**Comment by kushal555** [comment]
Hello @lucas3003   as I have multiple date picker in Datatable, So I need the change event but I can put the watch on ng-model because there is an array of models So Please let me know is there any change event available in the plugin ?
