### ISSUE TITLE
Date-format not working

### ISSUE THREAD

**Issue by Robouste** [720kb/angular-datepicker#203]
Hi, I tried to set a date-format but it doesn't work for me. Maybe it's something stupid but here is what I do : 

```html
<datepicker>
    <input ng-model="test" type="text" date-format="dd-MM-yyyy"/>
</datepicker>
```

And the output result when I chose a date : 

**Wed Mar 05 2014 00:00:00 GMT+0100 (Romance Standard Time)**

I tried severals date format like 'yyyy-MM-dd' or the one in the example but it is always showing the format above.

I tried with Google Chrome and Microsoft Edge.

Thanks for your help

**Comment by mindhells** [comment]
@Robouste  You have to apply the attribute to the "datepicker" tag instead the "input" one.
I made the same mistake.
Still I've a problem with the format: 
If you set an initial value to the model, the format is not applied but when you pick a new date it is...

**Comment by Robouste** [comment]
@mindhells Aha, I feel so stupid :) 
Now it works but I have the same problem as you. Not formatting with initial value.

I managed to fix it with a directive apply to the input : 

```javascript
widgetControllers.directive("dateTime", function ($filter) {
	return {
		require: "ngModel",
		link: function (scope, element, attrs, ngModelController) {

			ngModelController.$parsers.push(function (data) {
				//convert data from view format to model format

				return new Date(data);//converted
			});

			ngModelController.$formatters.push(function (data) {
				//convert data from model format to view format
				var dateFormat = "dd-MM-yyyy";
				var pDate = Date.parse(data);
				var result = "";

				if (data)
				{
					result = $filter("date")(new Date(pDate), dateFormat);//converted
				}

				return result;
			});
		}
	}
});
```

HTML : 

```html
<datepicker date-format="dd-MM-yyyy">
      <input date-time ng-model="myModel.date" type="text"/>
</datepicker>
```

I hope it helps :)

**Comment by 45kb** [comment]
Please use date-set="" to init date-format on load.

**Comment by 45kb** [comment]
Also, remember, Date format must be according to your browser locale, ```console.log(new Date(05-06-2013'))``` is not a valid date on my browser

**Comment by runxc1** [comment]
So the date-set is useful but very non intuitive as you have your date property as a Date object and have to set it using a string and looking through the issues there are a number of questions about this.   Seems a date-set-to-model or something would be very useful.   Putting something like this in the docs may also be helpful.

`<datepicker date-format="M/d/yy" date-set="{{model.dateProperty|date:'M/d/yy'}}">`
