### ISSUE TITLE
Howto: Disable weekends?

### ISSUE THREAD

**Issue by PavelPikat** [720kb/angular-datepicker#205]
How one would disable weekends in this datepicker? Is there such an option in through configs?

**Comment by roger2hk** [comment]
There is no such an option to disable weekends easily. You can generate the list of disabled dates and make use of `date-disabled-dates=""`.

You may want to take a look at Angular Material Datepicker component which contains the config `md-date-filter` for your filtering implementation.
https://material.angularjs.org/latest/demo/datepicker

**Comment by 45kb** [comment]
@PavelPikat Hi no option for this, you can disable an array of dates if you want as @roger2hk said.

Best.
