### ISSUE TITLE
date-disabled-dates populated properly but not greying out, sometimes works when refreshing

### ISSUE THREAD

**Issue by trivett** [720kb/angular-datepicker#206]
I am experiencing what seems like a race condition that there might be a solution to. In production, my `$scope.apartment.occupied_dates` is coming across as a properly formatted array and it is binding into the `date-disabled-dates` attribute. My template:

``` html
 <div class="col-sm-4">
    <label>Check-in</label>
    <datepicker
      ng-cloak
      date-format="MM/dd/yyyy"
      date-disabled-dates="{{apartment.occupied_dates}}"
    >
      <input type="text"
             name="checkin"
             validate-on="dirty"
             ng-model="booking.check_in"
             required
             required-message="'* Required'"
             class="form-control datepicker1 padding-6"
             placeholder="mm/dd/yyyy"
             >
    </datepicker>
</div>
```

When I inspect the datepicker element, it shows the array of dates that it should be greyed out on. When I refresh or open in a new tab, it works as expected. The issue doesn't present itself in development (Using Rails asset pipeline for what it's worth) making this especially hard to debug.

My guess is that the library writes the css rules for the disabled dates once, but does so prior to the `apartment.occupied_dates` getting a response from the server. Once it is there and injected into the html, it isn't changing the classes of the individual dates. 

My question is whether there is some way to delay this. I tried `ng-cloak` to no avail. I appreciate the help.

**Comment by 45kb** [comment]
@trivett Hi, if i understood your problem you should be waiting for the server response to init the datepicker, so `ng-if="scope.myDataFromBackend"` on the datepicker element will wait for that scope data and init the directive only when is data is ready.

Best.
