### ISSUE TITLE
Disable specific dates

### ISSUE THREAD

**Issue by kentcdodds** [720kb/angular-datepicker#21]
jQuery UI datepicker allows you to provide a function to determine whether a specific date should be disabled. I need this functionality. Is this something you could support?

**Comment by 45kb** [comment]
Hi @kentcdodds  shouldn't be too hard to create a new attribute (i.e: datepicker-disable="{{myArrayOfDates}}")  :)

I think this is a feature i didn't tought to already and i like it very much, i just need some time to do this.

**Comment by kentcdodds** [comment]
Terrific. With jQuery UI, they have you provide a function and I think
that's good because as the user navigates the calendar, that function is
called for each date to determine whether it's disabled. Otherwise the
array of dates would be huge.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by 45kb** [comment]
@kentcdodds  yes no problems i will introduce this feature, actually you already can set a date-min="" and date-max="" if you want to exclude a range of dates but i agree with you, we need it also for specific dates.

**Comment by 45kb** [comment]
@kentcdodds  Hi, sorry but i've been busy a lot, i needed to fix major bugs and probably i will need to check some others soon, if you have time feel free to create your own fork and try something out for this, any help appreciated, thank you.

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker#date-disabled

**Comment by kentcdodds** [comment]
Awesome. Thanks for doing that :-D

**Comment by 45kb** [comment]
@kentcdodds :+1:  If any further problem just write me back here, have a nice day

**Comment by zohaibmir** [comment]
Is there any way to disable all the dates except some specific dates.

**Comment by 45kb** [comment]
@zohaibmir  hi, there is no way at the moment, you can set a range of dates to be enabled but not specific dates.

**Comment by zohaibmir** [comment]
ok thanks.

**Comment by ROJAHEMA** [comment]
Hi,

`<datepicker date-format="dd/MM/yyyy" date-min="new Date()" selector="form-control">
	<input class="form-control" name="dateOfBirth" type="text"
	ng-model="farmer.dateOfBirth" placeholder="Date of birth"
	pattern="(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[012])/[0-9]{4}"
	ng-minlength="10" maxlength="10" required />`

I want to disable dates less than today.I have added code like above.But its not working
Please help
