### ISSUE TITLE
minimum-date-limit excludes the date from the calendar

### ISSUE THREAD

**Issue by mazzimi** [720kb/angular-datepicker#210]
I'm using the "date-min-limit" attribute to limit the lower date that can be selected on the calendar.
This is for example, to select the date a customer subscribed a specific offer. Of course the offer could not be subscribed before the first day it was available.

The problem is that if I set date-min-limit with the first dat of availability (let's say 2016-01-01), I can only choose the next day from the calendar (2016-01-02).
This seems to be non coherent with the description of this field and not coherent with the behaviuor you can expect.

So, now I have to calculate server side or javascript side the day before the first day and I have to use that date as "date-min-limit".
You understand this is not really desiderabile.

Thank you,
Michele

**Comment by thealein** [comment]
Hello,
I have exactly the same problem in my mobile view (in the web view everything works fine). 
Does anyone have a solution for that?

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/issues/167
