### ISSUE TITLE
not working in safari

### ISSUE THREAD

**Issue by SandeepSagar577** [720kb/angular-datepicker#211]
Hello All,

I'm using this datepicker for chrome, IE, FireFox & Safari, its working in all other browsers, except Safari

find error image here
![safari_datepicker](https://cloud.githubusercontent.com/assets/14272504/20213704/08871054-a830-11e6-9aa7-941d40033f53.png)

my code 

`                                                <datepicker date-format="MM/dd/yyyy" date-max-limit="{{Today | amDateFormat : 'YYYY-MM-DD'}}" date-min-limit="1900-01-01" selector="form-control">
                                                    <div class="input-group">
                                                        <input class="form-control input-sm" id="doi" ng-model="Practice.EHR.DateOfImplementation" placeholder="MM/DD/YYYY"/>
                                                        <span class="input-group-addon">
                                                            <i class="fa fa-calendar"></i>
                                                        </span>
                                                    </div>
                                                </datepicker>`

Thank you.

**Comment by 45kb** [comment]
Hi @SandeepSagar577 You're probably doing something wrong and maybe not related to the datepicker directive. Please give more infos about what's really happening.
Thanks
