### ISSUE TITLE
Trying to set restricted dates with date-disabled-dates

### ISSUE THREAD

**Issue by BishopOfTurkey** [720kb/angular-datepicker#215]
I have an array of dates which is pulled from a database.
It loads after the page loads

The end result when inspected with chrome dev tools is: 
`date-disabled-dates="["2017-01-01T13:00:00.000Z","2017-01-02T13:00:00.000Z","2017-01-03T13:00:00.000Z","2017-01-04T13:00:00.000Z","2017-01-05T13:00:00.000Z"]"`

I also have a date-min-limit set to the current day.

Just wondering if this is correct?

**Comment by 45kb** [comment]
@BishopOfTurkey Hi, i don't have much time to investigate now, is it working that way? Looks ok to me, but i could mistake actually...
