### ISSUE TITLE
Buttons directions

### ISSUE THREAD

**Issue by galrave** [720kb/angular-datepicker#216]
when using custom prevButton, nextButton the buttons images get reversed in the year selector

**Comment by lucas3003** [comment]
I could not replicate this problem.

![problem](https://cloud.githubusercontent.com/assets/3287486/21520807/9383193c-ccde-11e6-8378-1e723abed0f4.png)

**Comment by 45kb** [comment]
me neither @galrave  can you please describe how to? maybe i am missing something.

thanks @lucas3003

**Comment by 45kb** [comment]
closing, feel free to ask to re-open as you provide how to replicate the problem. thanks.
