### ISSUE TITLE
date-set="myModel.date" should be date-set="{{myModel.date}}" in docs

### ISSUE THREAD

**Issue by paddie** [720kb/angular-datepicker#22]
Just wasted an hour trying to figure this out.

```js
<datepicker date-set="myModel.date">
  <input ng-model="myModel.date" type="text"/>
</datepicker>
```
Should in fact be this for the angular-datepicker to pick it up:

```js
<datepicker date-set="{{myModel.date}}">
  <input ng-model="myModel.date" type="text"/>
</datepicker>
```

**Comment by 45kb** [comment]
@paddle Hi, sorry i probably don't get it, you don't need to set a default date in this case... your ng-model should update the input value without the use of date-set. You probably need date-format just to format the date ... or i'm missing something? :)

**Comment by 45kb** [comment]
@paddle hey thank you didn't noticed that, going to update readme!

**Comment by paddie** [comment]
No worries, it just took me for a spin :)

**Comment by 45kb** [comment]
@paddle ;) seriously if you can help feel free to PR

**Comment by paddie** [comment]
I'm actually pretty new to angular, so I also wanted to make sure I wasn't missing something :)

**Comment by 45kb** [comment]
:+1:
