### ISSUE TITLE
Default date is not displaying in calendar when min and max is set

### ISSUE THREAD

**Issue by mahiindsm** [720kb/angular-datepicker#220]
Hi ,
I am trying to set todays date in calendar(not in my input field) when I have max and min date is set.Please find my html code here.I see only max date shown when I opened the calendar.

//max and min hardcodeed here but I calculate it in my controller like todaysDate
        <datepicker  date-format="yyyy-MM-dd" selector="form-control"  date-min-limit="2001-01-01" date-max-limit="2020-01-01" date-set="{{todaysDate}}" date-set-hidden="true">

All I want is calendar should display todays date as default date when I set max and min dates in date picker.

I appreciate your help.

**Comment by mahiindsm** [comment]
I see below mentioned code in your  angular-datepicker.js.I am not sure why year is maxdate when maxdate is set in line # 744
 if ($scope.dateMaxLimit) {

          $scope.year = Number($filter('date')(new Date($scope.dateMaxLimit), 'yyyy'));//2014 like
        } else {

          $scope.year = Number($filter('date')(date, 'yyyy'));//2014 like
        }

**Comment by 45kb** [comment]
@mahiindsm Hi, this looks weird indeed, have you tried removing that piece of code? does it work as expected if you remove it?

thank you.

**Comment by mahiindsm** [comment]
I tried it. But no luck.

**Comment by krzyhan** [comment]
Have the same issue.

Tmp solution - set default date with `date-set=""`

**Comment by vaggelanos** [comment]
https://github.com/720kb/angular-datepicker/pull/291
