### ISSUE TITLE
Date-set value doesn't active the day slot in the date picker

### ISSUE THREAD

**Issue by akafaneh** [720kb/angular-datepicker#235]
I have this issue where the `date-set` value get assigned to the input text box but doesn't give the actual selected day in the datepicker the active cell properties (different background and font color).
This is an issue for me because i want to hide the input text box -where only will use it's value as it gets updated-, and when the user first get into the page will see as nothing is preselected though there is a default value from `date-set` attribute in the input text box (that is hidden as i said).
Any solution for that or a way to work around it.
thanks

![screenshot from 2017-01-24 11 44 58](https://cloud.githubusercontent.com/assets/24367872/22242339/a11c64a6-e22b-11e6-9d10-9ebad9503f0d.png)

**Comment by 45kb** [comment]
@akafaneh thanks for spotting this out! a PR would be appreciated here.

@tipycalFlow hey :) , do you know anything about this? Could it be a problem with the last changes?

**Comment by tipycalFlow** [comment]
@akafaneh could you share a plunker for this please and maybe try with an older version of the library (say 2.1.10)?

**Comment by akafaneh** [comment]
Thanks a lot for you prompt response, I'll try an older version first, then I'll share a plunker if i had the same issue.

**Comment by akafaneh** [comment]
I tried an older version and didn't work, it's a bit hard to do a plunker here because the work i've done on it's a a bit big, through what I already explained do you have any clue how to make the date-set value also active the actual datepicker day of it?

**Comment by tipycalFlow** [comment]
In that case, could you please share your html implementation of how you're using date-set?

**Comment by 45kb** [comment]
merging issue with https://github.com/720kb/angular-datepicker/issues/226
