### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by jjayaraman** [720kb/angular-datepicker#237]
After I upgrade to the latest version (2.1.13) from the previous (2.1.7), the date picker behaves strangely and  after selecting a date if populates a value 'Invalid Date' in the textfield. 

And shows as null & NaN in the Month & Year  dropdown at the top of the calendar.

**Comment by 45kb** [comment]
@jjayaraman does it works using this https://cdnjs.cloudflare.com/ajax/libs/angularjs-datepicker/2.1.12/angular-datepicker.min.js ?

**Comment by jjayaraman** [comment]
Yes it works fine with 2.1.12. Thanks.

**Comment by 45kb** [comment]
ok @jjayaraman that is something with the 2.1.13 going to delete that version just go with 2.1.12 ;) thanks to you

**Comment by dbelieves** [comment]
But 2.1.12 is not working on mobile.
I see invalid date error on my chrome.

**Comment by chrisdrew** [comment]
Don't forget to use datepicker-mobile="true"
