### ISSUE TITLE
Input autofocusing and opening datepicker

### ISSUE THREAD

**Issue by jonathanwiesel** [720kb/angular-datepicker#239]
I have a form with multiple fields, when the page loads the field with the datepicker automatically gets focused and the picker is toggled.

It doesn't matter if another field has the `autofocus` property set to true, the one with the datepicker gets focused.

**Comment by jonathanwiesel** [comment]
I've found that the problem is happening when the datepicker is inside a `form` tag, workaround for me was to substitute de `form` tag for a `div` tag with the `ng-form` attribute.

**Comment by 45kb** [comment]
yes @jonathanwiesel sometimes is just to trick it that way, it's quite impossible that the datepicker fits every website style and every element, just make some tries and trick it a little guys.

closing.
