### ISSUE TITLE
Invalid date in Mobile view

### ISSUE THREAD

**Issue by rishabhrawat11** [720kb/angular-datepicker#241]
Invalid date keeps on showing on Mobile.
(https://cloud.githubusercontent.com/assets/15124978/22728182/93b32146-ee02-11e6-9a1a-e25bcafc742d.jpeg)

**Comment by chrisdrew** [comment]
This is happening to me as well.

**Comment by rishabhrawat11** [comment]
Chris, I solved it  by changing the version by  2.1.9 and by setting the date-mobile ="true".

**Comment by chrisdrew** [comment]
@rishabhrawat11 I had to do datepicker-mobile="true" and that worked.
