### ISSUE TITLE
Bower version mismatch for release 2.1.12.tar.gz

### ISSUE THREAD

**Issue by roger2hk** [720kb/angular-datepicker#242]
The `bower.json` in [Source code (tar.gz)](https://github.com/720kb/angular-datepicker/archive/2.1.12.tar.gz) should be 2.1.12 instead of 2.1.11.

>\> bower install --save angularjs-datepicker
> bower not-cached    https://github.com/720kb/angular-datepicker.git#*
> bower resolve       https://github.com/720kb/angular-datepicker.git#*
> bower download      https://github.com/720kb/angular-datepicker/archive/2.1.12.tar.gz
> bower extract       angularjs-datepicker#* archive.tar.gz
> bower mismatch      Version declared in the json (2.1.11) is different than the resolved one (2.1.12)
> bower resolved      https://github.com/720kb/angular-datepicker.git#2.1.12

**Comment by 45kb** [comment]
@roger2hk you're right thanks for spotting it out, i am going to fix this

**Comment by 45kb** [comment]
ok use 2.1.13 👍  should work now

**Comment by roger2hk** [comment]
Confirmed OK in 2.1.13
