### ISSUE TITLE
The month before is loaded when I try to choose a day on current month

### ISSUE THREAD

**Issue by steven-github** [720kb/angular-datepicker#246]
1- I click on input to display calendar: https://screencast.com/t/2SYCMm5AML
2- I click on March 3 or anywhere outside the calendar and February month is loaded automatically: https://screencast.com/t/LypkCyK7xyJT

**Comment by 45kb** [comment]
@steven-github Hi, please if you can paste your html and library version, it doesn't seems to happen on my side using last version of the datepicker.

**Comment by steven-github** [comment]
I'm using "angularjs-datepicker": "2.1.13" on my package json, loading library from node_module directly and this is my html:

<div datepicker class="angular-datepicker" datepicker-class="angular-datepicker-container" date-format="yyyy-MM-dd" date-max-limit="{{maxDate}}" date-typer="true" date-refocus="true">
     <input ng-model="value" type="text" class="angular-datepicker-input form-control" prevent-keydown/>
</div>

**Comment by 45kb** [comment]
It doesn't seems to be a problem here, i just copied and pasted your html and i am using v2.1.14


![kapture-2017-03-04-at-20](https://cloud.githubusercontent.com/assets/7761650/23581858/e5f266aa-011d-11e7-8d06-49c041b47ff6.gif)
