### ISSUE TITLE
[Mobile] Calendar invalid date, not working

### ISSUE THREAD

**Issue by mayankaryan084** [720kb/angular-datepicker#247]
Hi,

I have used angularjs datepicker. its working fine but its not working fine for android and ios mobile. please find the below details for your reference. 

![image](https://cloud.githubusercontent.com/assets/22471782/23702889/43b3dfb4-0423-11e7-815e-dbe39d9c2146.png)

kindly help me to fix this issue. 

Thanks & Regards,
Mayank

**Comment by lftl** [comment]
As a followup, here's a very minimal example that fails for me in both Mobile Safari and Chrome for Android:

https://plnkr.co/edit/uc6SlaGVSuVpbOkx73mH?p=preview

**Comment by MoreBlood** [comment]
@mayankaryan084, try to add `datepicker-mobile="true"`
works fine for me

**Comment by lftl** [comment]
@MoreBlood that does seem to fix the issue:

https://plnkr.co/edit/LsOKxRSJeMTzSz0qBEy2?p=preview

I wonder why that fixes things, when the the documentation implies that that option defaults to true anyway.

**Comment by mayankaryan084** [comment]
@MoreBlood i have tried with it. but its working fine. Thanks a lot.

**Comment by mayankaryan084** [comment]
@MoreBlood i need one more help. for iphone data picker is not closing when we are trying to enter manually. can you please help me on it?

**Comment by MoreBlood** [comment]
@mayankaryan084 try to create custom event, and close it using code. For example adding display: none.

**Comment by mayankaryan084** [comment]
@MoreBlood thank you once again. its working fine.

**Comment by manideepcs024** [comment]
keeping mobile = true has worked for me perfectly!!!

**Comment by JohnnyTMD** [comment]
@MoreBlood thanks a lot, it worked for me.
