### ISSUE TITLE
[Mobile] months not being disabled

### ISSUE THREAD

**Issue by PizzaPete** [720kb/angular-datepicker#251]
Hello,

At a project here we've implemented the angular-datepicker. First of all, thanks for the great work.
Whenever we implement the Dutch localisation file we have some strange behaviour.

What we do is setting the min-date to current date - 4 months and max-date to current date + 4 months.
On the desktop version this works as expected. Whenever we switch to the mobile version it works, only the month 'oktober' (October in English) is not being de-activated and can be selected.

I've created a few JSFiddles to show the problem that is occurring.

1. [JSFiddle](https://jsfiddle.net/k3k53jwc/1/) with no localisation file that works correct.
2. [JSFiddle](https://jsfiddle.net/k3k53jwc/2/) with Dutch localisation file that doesn't disable the month selection for October.
3. [JSFiddle](https://jsfiddle.net/2yrt9ms2/) with Bulgarian localisation file that doesn't disable the month selection.

Are we missing something? Or is this really a bug?

**Comment by 45kb** [comment]
Hi @PizzaPete unfortunately it's a bug probably minor but must be checked. I see it doesn't work as expected cause Oktober is not disabled.

If you can or anybody can give this a check and send a PR we'll be much grateful, thanks.
