### ISSUE TITLE
Use datepicker-show with date-toggle as false didn't work

### ISSUE THREAD

**Issue by hmanprod** [720kb/angular-datepicker#253]
Hi Guys

I found an issue when using **datepicker-show** with **date-toggle** as **false**.
So when the first thing that i actually do is to set the visibility to **true**,
 i got looks like an empty calendar. The calendar seems to not be initialized correctly.
Check the screenshoot below to see how the bug looks like
![bug](https://cloud.githubusercontent.com/assets/1670599/24570546/9dfc4ade-1674-11e7-9da8-bb507f7773cd.png)

**Comment by 45kb** [comment]
@hmanprod Hi, the important thing is not to set date-toggle to false but instead you'll better not use it at all and only use datepicker-show, this example works https://github.com/720kb/angular-datepicker/blob/master/index.html#L45
