### ISSUE TITLE
Allow attribute use as well

### ISSUE THREAD

**Issue by tjsail33** [720kb/angular-datepicker#26]
To support browsers such as IE which restrict the types of elements allowed, allowing datepicker to be instantiated as an attribute as well would be great.

**Comment by 45kb** [comment]
@tjsail33  Hi i will check what's happening on IE, feel free to PR if you want, thank you for reporting

**Comment by 45kb** [comment]
@tjsail33  Same as for ui-bootstrap, since next version should restrict:AEC instead of E only can you try if this file fixs the problem please https://github.com/720kb/angular-datepicker/blob/ui-bootstrap-compatibility/src/js/angular-datepicker.js

thank you

**Comment by tjsail33** [comment]
That file did fix the problem for me, but only when i used the datepicker class on the element, as expected. If you could add a note about this to the docs that would be great before you merged.
