### ISSUE TITLE
Problem about Date format

### ISSUE THREAD

**Issue by FadiNouh1** [720kb/angular-datepicker#261]
I think there is a bug when using the the format of Austrian Calendar
I mean when I put the date format as ("dd.MM.yyyy") , the datepicker opens with flipping between the day and the month ,
ex : 03.04.2017 is initiated in the calendar as 4th of March , not as 3rd of April 
is there solution for this issue?

**Comment by PizzaPete** [comment]
Duplicate of #254

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/pull/257
