### ISSUE TITLE
Problems with datepicker on Firefox

### ISSUE THREAD

**Issue by curiousalok** [720kb/angular-datepicker#267]

**Comment by curiousalok** [comment]
I am usin 1.3 version of angular and your latest module from here

**Comment by curiousalok** [comment]
Issue is that when i want to bind that control with js to show a date from js i have used $filter to format date in js...
And it shows date perfectly fine in chrome but in firefox it shows invalid why?

**Comment by curiousalok** [comment]
can anybody pls help what i am doing wrong??
why this tool is working perfectly fine with chrome but misbehaving with firefox?

**Comment by curiousalok** [comment]
and one more issue once i click the box the calendar appears and it appears until i click another control it is not disappearing when click outside. and its disappearance takes time why?somebody pls help here is mycode:

 <datepicker date-set="{[{end}]}" date-format="dd/MMMM/yyyy" >
          <input ng-model="poid.enddate" name="enddate"  readonly="true" type="text" id="enddate" required="" placeholder="End Date"  class="formtabletxt1"/>
        </datepicker>

**Comment by 45kb** [comment]
@curiousalok hi, it could be anything, can you please create a live jsfiddle or plnkr in order to help you further?

thanks.

**Comment by curiousalok** [comment]
The issue is solved mate thanks for reply....the reason was conflict between some files
