### ISSUE TITLE
Calendar opens after initialize and close when i lose focus

### ISSUE THREAD

**Issue by gkoma** [720kb/angular-datepicker#269]
On my website i have many datepickers. For faster loading i want to initialize only the  one with element that will be focused
 
In that configuration i need to click once again on initialized item to open it. How can i achieve effect when calendar opens after initialize and close when i lose focus (eg. click on something else).

**Comment by 45kb** [comment]
Use ng-if="" on the datepicker element, that way if ng-if="true" the directive is initialized again.
