### ISSUE TITLE
how to convert pdf to doc in angular?

### ISSUE THREAD

**Issue by curiousalok** [720kb/angular-datepicker#271]
I have created a pdf file with the module jspdf(), now i was told to convert this word is there a way to convert whole pdf to doc??

**Comment by 45kb** [comment]
@curiousalok wrong repository :)

**Comment by curiousalok** [comment]
Sorry for that can you please delete this?

**Comment by 45kb** [comment]
@curiousalok no problems but it's impossible to delete issues on github, just edit it in case
