### ISSUE TITLE
Datepicker format

### ISSUE THREAD

**Issue by daniel94104** [720kb/angular-datepicker#275]
I see there is a date-format option in the DOC, but I wonder where to put the option in. Input element? Controller?

Also, I have read some post said we could write a directive(attribute) to format the date. However, since there is already a option written here, I am curious where to use the option. 

Thanks!

**Comment by 45kb** [comment]
Just put it on the directive itself @daniel94104 

for example

```html
<datepicker date-set="the date you want">
<input ng-model="date" type="text"/>
</datepicker>
```
