### ISSUE TITLE
How to set week start from monday

### ISSUE THREAD

**Issue by anu111** [720kb/angular-datepicker#30]
As default week starts with sunday

**Comment by wouldgo** [comment]
ATM there is no way to manage the first day of the week.
As a starting point, feel free to propose a way to manage this requirement.

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/pull/73 this could help as soon as it's valid

**Comment by pallatee** [comment]
+1

**Comment by Rookson** [comment]
To make week start on mondays, do the following two steps in angular-datepicker.js

1. When calculating `$scope.daysInString`, set the new Date String from `'06/08/2014'` to a monday, like `'06/09/2014'`.

2. In `function setDaysInMonth`, update the calculation of firstDayMonthNumber and lastDayMonthNumber:

 - `var firstDayMonthNumber = (new Date(year + '/' + month + '/' + 1).getDay() + 6) % 7;`
 - `var lastDayMonthNumber = (new Date(year + '/' + month + '/' + limitDate).getDay() + 6) % 7;`

**Comment by davidsandoz** [comment]
I see that the PR #73 is not valid and hasn't been fixed.
Moreover it conflicts with master as it is quite old.

Is there any plan to implement that on @720kb side? Otherwise I'd like to try making a new PR.

**Comment by davidsandoz** [comment]
I did the PR #198 with the implementation of the feature. Did you had time to look at it? Is there anything I can still improve?

**Comment by davidsandoz** [comment]
Now that #198 is merged, you can use the option `date-week-start-day` to set the week start to Monday.

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/pull/198
