### ISSUE TITLE
Month and year is displayed as Undefined and null after update

### ISSUE THREAD

**Issue by ariesbrunetyson** [720kb/angular-datepicker#32]
I tried to update the datepicker using bower. Once updated it was showing undefined and null for month and year.

**Comment by 45kb** [comment]
Hi @ariesbrunetyson  just realesed a new version (https://github.com/720kb/angular-datepicker/releases/tag/0.2.2) try to update bower in a while again.

Could you please paste your html code so that i can investigate it better ?

Thank you

**Comment by 45kb** [comment]
@ariesbrunetyson  still you having troubles?

I released a newer version https://github.com/720kb/angular-datepicker/releases/tag/0.2.3

Try to update from bower or use the latest version cause i found many new bugs and fixed them.

I close the issue for the moment.
