### ISSUE TITLE
Not handling next-month invalid dates

### ISSUE THREAD

**Issue by tjsail33** [720kb/angular-datepicker#33]
Not really sure how to title this, but here goes.

Today is January 29th. If you init the datepicker to today, open it, and hit the arrow for next month, you would expect February to be displayed, correct? 

Here's the issue. 2/29 is NOT a valid date this year. The datepicker shows March in the header for both February and March as a result.

**Comment by 45kb** [comment]
@tjsail33  Hi , thanks for reporting, are you using the latest datepicker version/release?

Also could you provide your code so that i can investigate better, i tried replicating your scenario but it seems to work for me.

Let me know thank you.

**Comment by 45kb** [comment]
I forgot to tell you... just for your personal info, there is no need to init datepicker to today date, cause by default it will inherit and select the today date :)

**Comment by tjsail33** [comment]
```jade
.date(custom-datepicker, date-format="EEE MMM dd", style="float: left;")
    input.end-date(ng-model="datepicker.date", type="text", readonly, placeholder="Due Date...")
```

I am using the most recent version, I have simply changed the module name due to a conflict with another library. I logged a few times during $scope.nextMonth() and can confirm that it was trying to use 2015/2/29 as a valid date, which is wrapped around to March 1st by JSDate because 2015/2/29 is not a valid date.

**Comment by 45kb** [comment]
@tjsail33  Sounds weird, i tried replicating what you say, today (yesterday) 29th January selected by default, move to next Month i see no problems, i get February as next month and day is not selected so you have to click a new day to select it.

this is the html i use:

```html
<datepicker date-format="EEE MMM dd" date-set="2015/02/29">
<input ng-model="date" readonly type="text" placeholder="Select a date...."/>
</datepicker>

**Comment by 45kb** [comment]
@tjsail33  Sounds weird, i tried replicating what you say, today (yesterday) 29th January selected by default, move to next Month i see no problems, i get February as next month and day is not selected so you have to click a new day to select it.

this is the html i use:

```html
<datepicker date-format="EEE MMM dd" date-set="2015/01/29">
<input ng-model="date" readonly type="text" placeholder="Select a date...."/>
</datepicker>
```

What you would achieve?

Still not clear to me, sorry .... i want to help but try to explain better the problem 

Can you please write down also which version are you using, is it 0.2.3 ?

**Comment by 45kb** [comment]
2015/02/29 is not a valid date worldwide....

**Comment by 45kb** [comment]
@tjsail33  Going to close the issue, if you still facing problems let me know.
