### ISSUE TITLE
month is undefined when press next button

### ISSUE THREAD

**Issue by milindsaraswala** [720kb/angular-datepicker#34]
I just downloaded and run on firefox index.html file where I found that when I press next button month name is undefined and after that month name never appear.
![1](https://cloud.githubusercontent.com/assets/479750/5987345/7207cf2e-a935-11e4-91af-21c6858a6763.JPG)
![2](https://cloud.githubusercontent.com/assets/479750/5987346/752075d0-a935-11e4-9347-146cc517da97.JPG)

But same thing works in google chrome but there in first input box don't show next and previous button properly
![3](https://cloud.githubusercontent.com/assets/479750/5987351/c451bfba-a935-11e4-80c3-4fbd4478dc24.JPG)

What is the issue, Kindly can you explain.

I only change href from "//.... to "http://.... part on index.html that's it.

**Comment by 45kb** [comment]
Hi @milindsaraswala  i fixed the Firefox bug sorry for that, you can use the latest version https://github.com/720kb/angular-datepicker/releases/tag/0.2.4 

For the icons, be sure you are running a webserver and check if any 404 in console...

Let me know if i can close the issue, thank you for reporting

**Comment by milindsaraswala** [comment]
Thank you very much, now everything is working on FireFox without webserver, But on chrome still same.

After you update files, can I use bower in my angularjs project

**Comment by 45kb** [comment]
@milindsaraswala  can you paste the html code , the full page with css and js files links please.

Are you using file:// protocol to browse ?

**Comment by milindsaraswala** [comment]
Yea it was issue with file protocol. Thank you for your support
