### ISSUE TITLE
Display calendar wihtout click on directive input

### ISSUE THREAD

**Issue by stigmat4j** [720kb/angular-datepicker#35]
Hello.
I need to display the calendar on screen without clicking on directive 'datepicker'. Could you tell me how to do it?

Thank you.

**Comment by wouldgo** [comment]
Hi,
ATM the only way to display the datepicker is to focus (or click) the input wrapped by directive.
The only way to reach that behavior with the actual codebase is to use the `triggerHandler()` method on the element wrapped. Anyway this kind of functionality is out of actual scope of the implementation.

If you want to outline a way to manage this requiremen feel free to propose your point of view.

**Comment by stigmat4j** [comment]
I need to display the calendar constantly for choosing the date. (see screenshot). For example, bootstrap datepicker has a setting isInline and the calendar is always displaying.

![screenshot](http://habrastorage.org/files/ebf/c9c/252/ebfc9c252d9a4dbd9a0af859a078ecfc.png "screenshot")

**Comment by 45kb** [comment]
@stigmat4j  Hi, we will introduce very soon a solution for that,  in case you need it urgently just fork the repo and PR, that could be great!

**Comment by daniellecs** [comment]
Hi @45kb , 

I was wondering if you've reached a solution for this? I as well am wanting to show the calendar constantly without click of an input field. Let me know! Thank you.

**Comment by isaacwastaken** [comment]
All you have to do is edit the CSS file really...currently the calendar is set to a position=absolute and visibility=hidden ; change position to block, and position to relative... Edit the directive code as needed to take care of the click events..

**Comment by 45kb** [comment]
Yes, thank you @isaacwastaken  it's just a matter of CSS because the datepicker already exists in page, it is just hidden. :+1:  

just change this https://github.com/720kb/angular-datepicker/blob/master/src/css/angular-datepicker.css#L48 to visibility:initial; or visibility:visible;

**Comment by piyushchauhan2011** [comment]
:+1:  Works perfectly.
