### ISSUE TITLE
i18n problems

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-datepicker#36]
i18n check, improvements.

Any help appreciated.

**Comment by jonataswalker** [comment]
Hey bro, thanks for your piece of code.

I just included i18n (angular-locale_pt-br) and the datepicker got it right.

Again, thank you.

**Comment by 45kb** [comment]
@jonataswalker  Hi :)
That's weird, actually this was/is a known bug, but if it works i am glad :+1:

**Comment by wouldgo** [comment]
Yes, I think it's quite weird too because I've some scenarios where the localization didn't work... need more time to investigate well.

**Comment by jonataswalker** [comment]
That's it.

![workspace 1_011](https://cloud.githubusercontent.com/assets/10571881/6734365/9007debc-ce36-11e4-80e4-d86808a864d8.jpg)

**Comment by 45kb** [comment]
@jonataswalker  thank you for sharing :+1:

**Comment by jonataswalker** [comment]
(y)

**Comment by 45kb** [comment]
Looks ok, you may re-open this issue at anytime if needed

**Comment by benIT** [comment]
experiencing same issue,[including French locale](https://github.com/angular/bower-angular-i18n/blob/master/angular-locale_fr-fr.js) solved it!
Thanks guy!

**Comment by DsanchezPerez** [comment]
I am experiencing an issue with the validation of  datepicker and short date format.  It seems that the value returned from the calendar is a string that is not converted into a valid date object cause the value to be invalid for any locale except for USA/default.
