### ISSUE TITLE
 i18n better support

### ISSUE THREAD

**Issue by octavioamu** [720kb/angular-datepicker#37]
When i18n is added the calendar can't handle the correct dates with filters, maybe a separation of between the date without format and the date with format like proposed in #11 can be a work around for this. 
 
http://plnkr.co/edit/2YPKdJ5owuZUobQqrIKI?p=preview

**Comment by wouldgo** [comment]
Referred also to #36

**Comment by octavioamu** [comment]
Yes @45kb ask me to create the issue

**Comment by wouldgo** [comment]
No problem, I made a referral for sake of simplicity.

Thanks

**Comment by 45kb** [comment]
Hi guys i just close this but we can all refer to https://github.com/720kb/angular-datepicker/issues/36
