### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by rvanbaalen** [720kb/angular-datepicker#38]
Please be more specific about Internet Explorer support instead of just showing a '?' icon in the README. Which versions are (not) supported and why?

I want to use this in production but need a certain level of Internet Explorer support (IE9 at least).

**Comment by wouldgo** [comment]
Good evening @rvanbaalen,
we never tested on IE and honestly I don't even know if there are some issues (I suppose they could be mainly related on CSS) since we've never considered that for our target release and we gave priority to other improvements.

If you can help us in supporting IE we appreciate.

**Comment by ariesbrunetyson** [comment]
@rvanbaalen,  I'm using this in IE 11. I never faced any major issue. I've faced a minor issue which is related to accessibility through keyboard navigation. That also has minimal support. I'm not sure about IE 9 in specific. But I believe it should work well.

**Comment by wouldgo** [comment]
Thanks for the information @ariesbrunetyson, 

farther If there are some issues on IE9 and there are doubts about the way to achieve a good solution, here it's the best place to review, discuss and reach a good result :v:

**Comment by wouldgo** [comment]
Hi @rvanbaalen and @ariesbrunetyson,

#43 does an improvement for IE9+ thanks to @Saviio.

**Comment by sourcebits-kirthanasg** [comment]
Hi, is there anything that can be done to make it work in IE8. I really like this plugin but i should support IE8 as well. I tried downgrading the angular version and it still works fine in other browsers. I just want to know if with some effort from my side,i can make it work on IE8 or it is completely out of scope. Thanks..

**Comment by 45kb** [comment]
@sourcebits-kirthanasg Hi, for sure.... you can try, we'll be much glad if you add this support.

From the angularjs side there should be no problems supporting IE8.

**Comment by rvanbaalen** [comment]
@45kb 

> From the AngularJS side there should be no problems supporting IE8.

Except for the fact that the last two major versions (since 1.3) of AngularJS have dropped IE8 support alltogether.

**Comment by 45kb** [comment]
@rvanbaalen  Hi, indeed the only way is to declare everything in README, if you need IE8 support include an older angular version for example...

**Comment by rvanbaalen** [comment]
I would just say there is something seriously wrong with your project and/or client if they need IE8 support that bad.

IE8 + AngularJS -> You don't want to go there.

There have been so many improvements since AngularJS 1.2, you basically can't simply downgrade or other components of your project start to fail.

For now I'll go ahead and close this issue. I'm a team member of Angular UI now so my focus is with the UI Bootstrap datepicker.
