### ISSUE TITLE
How to localize or translate?

### ISSUE THREAD

**Issue by itonics-tbeauvais** [720kb/angular-datepicker#39]
It seems that the date picker is using $locale but I haven't found that switching language is reflected in the date picker.

Is there any documentation on how to facilitate this?  

Any insight would be greatly appreciated, thanks!

**Comment by 45kb** [comment]
@itonics-tbeauvais  Hi, we opened an issue for that, it needs a check on what is happening cause probably something is not allowing the translations (some variable probably), if you want to try something helping us we'll be much grateful.

i close this  just refer to this issue (https://github.com/720kb/angular-datepicker/issues/36)

**Comment by itonics-tbeauvais** [comment]
Thanks, I will take a look when I am able.  I'll follow the other issue. Thanks.

**Comment by 45kb** [comment]
@itonics-tbeauvais no problems, thank you a lot!

**Comment by minasvisual** [comment]
Hi people, i solve this! Just import angular locale file after angular.js, available on angular i18 link:

https://github.com/angular/angular.js/tree/master/src/ngLocale
