### ISSUE TITLE
Firefox issue on changing month

### ISSUE THREAD

**Issue by wouldgo** [720kb/angular-datepicker#42]
We spot this issue on Firefox: if an user selects a date then change the month, the current displayed month in the datepicker header became *undefined*. If the user selects a new date the displayed date in the input is correct.

**Comment by RomeroDiver** [comment]
Hi, why are You using '/' as deliminator for creating a new Date()? This is the reason why Firefox is displaying *undefined*. If You change this one to '-' then it works ok on Firefox, as well as Chrome. I cannot check this on Safari, but I assume if it works on Chrome it should work on Safari as well.

**Comment by 45kb** [comment]
@RomeroDiver  Hi thank you for reporting a fix, would you please create a PR to show the fix?

Thanks once more.

**Comment by RomeroDiver** [comment]
Yes, but later today.

**Comment by 45kb** [comment]
@RomeroDiver  for sure, when you can! thank you a lot :+1:

**Comment by RomeroDiver** [comment]
I found out that the problem was with creating a new Date in general. When You are adding values, Firefox cannot create a date when month has only one digit. I fixed this, and also added the fix from #51 but I cannot create a branch - I get 403. Do You maybe know what's wrong?

**Comment by 45kb** [comment]
@RomeroDiver  just fork the repo and you can do it ;)

**Comment by RomeroDiver** [comment]
Not sure if You saw my comment for the change, so I will add it here as well: as far as I can understand, $scope.monthNumber starts from 1, not 0. And for Date constructor we need to provide month starting from 0 - that 's why i use monthNumber-1. Maybe a better sollutiona would be to change the monthNumber variable to start from 0, unfortunately at the moment I don't have time to do this

**Comment by wouldgo** [comment]
Hi @RomeroDiver,

@45kb and I disccus about your intervents that, as far as I understand, reside here: https://github.com/RomeroDiver/angular-datepicker/pull/1.

If you open a pull request towards this repository with your commit we'll merge considering to manage next steps issues as you report in the previous comment.

Could you please make the PR?
Thanks a lot for your commitment

Dario

**Comment by wouldgo** [comment]
closed with #57
