### ISSUE TITLE
put input outside of the directive

### ISSUE THREAD

**Issue by apansky** [720kb/angular-datepicker#45]
First of all thanx for wonderful plugin.
is there any change to put input outside of the directive? 

thanx !

**Comment by 45kb** [comment]
Hi @apansky 

At the moment is not possible, the directive wrapper tag was intended to keep the datepicker isolated from the rest of the html page and for the CSS style to be more "stable" .... less troubles at all.

If you want you can easily fork the project and do what you want, if you do something let us know, help is much appreciated!

Thank you
