### ISSUE TITLE
set date-min-limit not working properly

### ISSUE THREAD

**Issue by codeOfThomasRutzer** [720kb/angular-datepicker#46]
Hi, maybe I have a very weird issue here but:

I have this in my controller:
`$scope.minDate = new Date();`

And this is the directive:
`<datepicker date-min-limit="{{minDate}}" date-format="dd.MM.yyyy">
      <input ng-model="event.date" type="text" readonly />
 </datepicker>`

But somehow, the min-limit is not working...

Thanks in advance for any help

**Comment by sijo-vijayan** [comment]
In controller 

    $scope.minDate = new Date().toString(); // If you want to set current date

In the html

    <datepicker date-min-limit="{{minDate}}" date-format="dd.MM.yyyy"> <input ng-model="event.date" type="text" readonly /> </datepicker>

**Comment by alteredorange** [comment]
This isn't working for me... I can set max-limit just fine, but I can't get min Limit to work with this exact same code, it just makes nothing selectable.

**Comment by sijo-vijayan** [comment]
Can you share your code or make a jsfiddle ?

**Comment by alteredorange** [comment]
Doh, sorry, forgot to come back and delete my comment, I was just doing it wrong :) :+1:

**Comment by akshay-bbytes** [comment]
Worked Fine for me  thanks @sijo-vijayan

**Comment by akshay-bbytes** [comment]
@codeOfThomasRutzer - i tweak the code in such a way it worked fine

 $scope.minDate = moment(new Date(), 'DD-MM-YYYY').toISOString();

use moment js to convert date format.

**Comment by akshaynagpurkar** [comment]
@codeOfThomasRutzer  - i tweak the code in such a way it worked fine

$scope.minDate = moment(new Date(), 'DD-MM-YYYY').toISOString();

use moment js to convert date format.

**Comment by akshay-bbytes** [comment]
@codeOfThomasRutzer I tweak code such a way its disabling all past dates
Try this code, it worked fine for me

```
<datepicker date-format="dd-MM-yyyy" selector="form-control" date-min-limit="{{minDate}}">
$scope.minDate = new Date().toDateString();
```

**Comment by ad08star** [comment]
there is one extra thing to notice,
if we use $scope.minDate = new Date().toString(); datepicker might disable the current date too
so its better to use $scope.minDate = new Date().toDateString();
it took me almost 2 days to figure this out... :)
