### ISSUE TITLE
date-set feature uses current calendar month layout for all months

### ISSUE THREAD

**Issue by codeocelot** [720kb/angular-datepicker#47]
I think I've found a bug.  Setting date-set to a date not in the current month will produce an incorrect month format.  

For example, see [a quick plunker](http://plnkr.co/edit/McPbktfeVdSBvRN50JXE?p=preview).  Notice that the displayed calendar starts on Sunday, where May actually starts on a Friday (see screenshot of my korganizer calendar)
![calendar](https://cloud.githubusercontent.com/assets/4086894/6878433/4279843c-d49b-11e4-9099-018f18db06a1.png).

I suspect that the date is being set using the current month's date (March 2015 starts on a Sunday). 

I'll see what I can do to fix this, and submit a change.  I'd appreciate any suggestions on how you'd prefer this being solved!

**Comment by 45kb** [comment]
@codeocelot  Hi, thank you a lot for the fix, i am going to merge it.

Actually, thanks to your fix i've checked better date-set attribute, and discovered another little bug (when you date-set="05/05/2035") you'll see opening the years pagination that 2035 is not in front of you as selected year.
