### ISSUE TITLE
Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by sdlfjhlaskdjfhlaskjdfh** [720kb/angular-datepicker#51]
Anytime I click in the page or interact with the datepicker, the following shows in the console'

    Uncaught TypeError: Cannot read property 'className' of null

On line 354;

    theCalendar.classList

`theCalendar` doesn't seem to exist, but everything is running as expected. I just get the error in the console.

**Comment by sdlfjhlaskdjfhlaskjdfh** [comment]
I found the solution. The `$(window)` click function needed an check against `theCalendar` to ensure that it existed (not null) before hiding it. 

    angular.element($window).bind('click', function onClickOnWindow(e) {

        if (!isMouseOn && !isMouseOnInput && theCalendar) {
            $scope.hideCalendar();
        }
    });

**Comment by 45kb** [comment]
@sdlfjhlaskdjfhlaskjdfh Hi, thanks for the fix and for reporting this issue, could you please make a PR so we can merge the changes? :+1:

**Comment by wouldgo** [comment]
closed with #57
