### ISSUE TITLE
Min/max date is not dynamic

### ISSUE THREAD

**Issue by RomeroDiver** [720kb/angular-datepicker#58]
Hi,
as far as I can see, min and max date are not dynamic values - there is no possibility to add two datepickers on the page, and  set the value of the first as minDate and the second as maxDate?
Are You planning to add such functionality?

**Comment by RomeroDiver** [comment]
Sorry, these values are dynamic, the problem must be with my usage.

**Comment by 45kb** [comment]
@RomeroDiver  no problems, if you find some fix for anything feel free to PR! 
Same if you need help just ask :+1: 

thank you.
