### ISSUE TITLE
Hiding  calendar in Firefox

### ISSUE THREAD

**Issue by RomeroDiver** [720kb/angular-datepicker#60]
Hi once again,
hiding calendar in Firefox is not working, as *focusout* event is not supported by the browser.([link](https://developer.mozilla.org/en-US/docs/Web/Events/focusout#Browser_compatibility))
Why do You use these two variables - **isMouseOnInput** and **isMouseOn**? Why not use a simple flag *isCalendarOpened* and set it to true when showing the widget? If You agree with such change, I can create a PR for this.

**Comment by 45kb** [comment]
@RomeroDiver  Hi, the isMouseOnInput and isMouseOn were thinked for to not use on(blur).

If your changes are not going to change the user interaction with the datepicker itself, we'll be much glad about a PR!

**Comment by 45kb** [comment]
Is it working, try and report if any other problem, you may re-open the issue if you need.
