### ISSUE TITLE
Customized selector is not working "selector="form-control""

### ISSUE THREAD

**Issue by rrajesh145** [720kb/angular-datepicker#62]
Hi,
When i tried to use the code which you have mentioned to customize the selector it is not working for me . 
Note : I have included bootstrap css and js file in my page

Code which i tried is below :
 <datepicker date-format="yyyy-MM-dd" selector="form-control">
        <div class="input-group">
          <input placeholder="Choose a date">
          <span class="input-group-addon" style="cursor: pointer">
            <i class="fa fa-lg fa-calendar"></i>
          </span>
        </div>
      </datepicker>

**Comment by 45kb** [comment]
@rrajesh145  Hi sorry but you posted half message, could you please fix it so that we can understand what you are talking about?

thank you :+1:

**Comment by rrajesh145** [comment]
Sorry dont know y it happens , below is the code which i tried to use :

  <datepicker date-format="yyyy-MM-dd" selector="form-control">
        <div class="input-group">
          <input placeholder="Choose a date">
          <span class="input-group-addon" style="cursor: pointer">
            <i class="fa fa-lg fa-calendar"></i>
          </span>
        </div>
      </datepicker>

**Comment by rrajesh145** [comment]
Sorry i forget to do  Markdown of the code thats y it is missed :+1:  
Below is the code which i tried to use . Css is not getting applied to this date picker
 
  `<datepicker date-format="yyyy-MM-dd" selector="form-control">
        <div class="input-group">
          <input placeholder="Choose a date">
          <span class="input-group-addon" style="cursor: pointer">
            <i class="fa fa-lg fa-calendar"></i>
          </span>
        </div>
      </datepicker>`

**Comment by 45kb** [comment]
@rrajesh145  Hi, could you please make some jsfiddle or plunkr to understand better your use case?

From a quick look i saw you wrapping everything inside the <datepicker> tag, usually that tag should wrap only the <input> element.... 

Let know please

**Comment by shankar-mits** [comment]
I am having the same issue, I use foundation.css and here is my snippet
`<datepicker date-format="MMMM d, y", date-max-limit="#{currentDate}", selector = "fa-calendar">
         <input type="text", name='dob' ng-model="dateOfBirth" placeholder ="Date Picker">
         <i class ="fa fa-calendar">
    </datepicker>`

clicking on calendar icon shows datepicker, but input field isnot filled.

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/issues/71

**Comment by 45kb** [comment]
@shankar-mits Hi, may i ask you to provide a jsfiddle or plunkr example to investigate this problem?

Thank you a lot.

**Comment by shankar-mits** [comment]
Here is the fiddle 
http://jsfiddle.net/561dc0jz/2/

**Comment by shankar-mits** [comment]
@45kb Can I have the solution?

**Comment by 45kb** [comment]
@shankar-mits Hi, actually there is no solution ready, the datepicker is binded on the input click/focus, feel free to PR something if you try anything, we will try fixing this but we need some time unfortunately.

**Comment by funzeye** [comment]
Hey, im guessing it's not working for you becuase you are saying selector is form-control but you dont have any input below that with a class of form-control!! Simple as.
In fairness to you the code sample on the home page is wrong - he doesn't include the class="form-control" in the input
