### ISSUE TITLE
Formatting on scope update

### ISSUE THREAD

**Issue by FeminismIsAwesome** [720kb/angular-datepicker#64]
<datepicker format="MM/dd/yyyy">
  <input ng-model="date" type="text"/>
</datepicker>
<button ng-click="setToToday()">
   Set To Today
</button>
// controller
function exampleController($scope) {
  $scope.setToToday = function() {
      $scope.date = new Date();
  }
}

Right now, this won't reformat into MM/dd/YYYY but leave unformatted. Is there a way to get it to reformat when the date is set by a user action (like clicking a button), or is that not behavior supported currently? What would your objections be to me trying to add this feature?

Cheeers,
Ian

**Comment by 45kb** [comment]
@FeminismIsAwesome  Hi, did you tried date-format="" date-set="" attributes? Isn't this good for your scope?

**Comment by WillBrindle** [comment]
I believe what they mean is if I do:

<datepicker date-format="MM/dd/YYYY">
<input type="text" ng-model="date" />
</datepicker>

Then in the javascript I set date, the value appears unformatted in the box. It remains unformatted until you pick a date with the picker.

**Comment by FeminismIsAwesome** [comment]
Sorry for taking so long to get back to this; but yes @WillBrindle that is exactly what I meant. I can produce a demo of the issue i'm seeing by tommorrow, to better help demonstrate what's wrong.

**Comment by evdoks** [comment]
I am experiencing exactly the same issue: when the model is prepopulated, the formatting is ignoring until a date is selected.

**Comment by evdoks** [comment]
The issue seems to be related to this [issue](https://github.com/angular-ui/bootstrap/issues/2659).

**Comment by 45kb** [comment]
Hi guys can you please send an example of what you are trying to do, from my test everything looks ok, but i may be missing something...

thank you :100:

**Comment by SyatesAurora** [comment]
Right at the bottom of angular-datepicker.js

You'll see

$scope.paginateYears($scope.year);
$scope.setDaysInMonth($scope.monthNumber, $scope.year);
add
$scope.setInputValue(); after those lines.

This will fix the problem with values being preset.

You may be able to add a $watch to fix your problem and just call $scope.setInputValue();

**Comment by kim0z** [comment]
Hi, I select a date from DatePicker, and I can see the format as expected e.g. November 5, 2015, when save the date into DB it will be saved e.g. 2015-11-18T22:00:00.000Z. 

When I retrieve the data from DB and want to show it again into the input it shown as saved in DB.

the issue is: 
1. I want to see the date as November 5, 2015 when got it from DB.
2. I want to make sure that when save again to save the original date :  2015-11-18T22:00:00.000Z. 

Any idea?

**Comment by 45kb** [comment]
Hi, my quick/dirty suggestion would be to use  `date-format="" and date-set="{{dbDatetime}}"`, then before saving and after retriving the date from DB change it on the fly from your controller like this: `$filter('date')($scope.dbDatetime, 'longDate');`

Hope it helps, if not enough please share a fiddle or plnkr with your code i'll be in touch to help.

**Comment by kim0z** [comment]
Hi, thanks for the fast answer.
        <td>
                                <label class="label1">Start date:</label>
                            </td>
                            <td>
                                <datepicker date-format="MMMM d, y" style="position: absolute; width: 100px; height: 150px;">
                                    <input name="inputStartDate" ng-model="dateStart" type="text"
                                           ng-blur="onBlur($event)"/>
                                </datepicker>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="label1">End date:</label>
                            </td>
                            <td>
                                <datepicker date-format="MMMM d, y" style="position: absolute; width: 100px; height: 150px;">
                                    <input name="inputEndDate" ng-model="dateEnd" type="text" ng-blur="onBlur($event)"/>
                                </datepicker>
                            </td>
                        </tr>

Controller:

  $scope.dateStart = $scope.tripById[0].start_date;
  $scope.dateEnd = $scope.tripById[0].end_date;


response from server: 
[{"id":104,"trip_name":"Really","start_date":"2015-11-04T22:00:00.000Z","end_date":"2015-11-18T22:00:00.000Z","continent":["America"],"cities":null,"trip_description":"hello my great APP","cities_list":null,"table_plan":[{"city0":"haifa","days0":"1","general0":{"flight":"","hotel":"","car":"","action1":"","action2":""}},{"city1":"london","days1":"3","general1":{"flight":"","hotel":"","car":"","action1":"","action2":""}}]}]

If you can help with exact change that I can do :), Thanks.

**Comment by 45kb** [comment]
I guess you just have to inject `$filter` in your controller (or whatever you using) then:

```javascript
$scope.dateStart = $filter('date')($scope.tripById[0].start_date, 'MMM d, y');
$scope.dateEnd = $filter('date')($scope.tripById[0].end_date,'MMM d, y');
```

If it doesn't works  (i have actually no way to test it) try like this:

```javascript
$scope.dateStart = $filter('date')(new Date($scope.tripById[0].start_date), 'MMM d, y');
$scope.dateEnd = $filter('date')(new Date($scope.tripById[0].end_date),'MMM d, y');
```

**Comment by kim0z** [comment]
Exactly what I wanted, the first option worked, Thank you @Filippo

**Comment by 45kb** [comment]
You're welcome :+1:  glad if it works!
