### ISSUE TITLE
Date-Set attribute is not working.

### ISSUE THREAD

**Issue by RahulGarg142** [720kb/angular-datepicker#66]
<datepicker date-set="2018/07/14">
                          <input type="text" ng-model="date"/>
                        </datepicker>

I am using simple example but unable to set the default date, date limits are working well.
I am using  angularjs v1.3.15 and working on chrome.

**Comment by 45kb** [comment]
Hi @RahulGarg142  it is fixed now, as by commit (https://github.com/720kb/angular-datepicker/issues/66) it was missing the setInputValue() when setting a default date the input value was empty, so now you can see the input value is correct.

On the demo page (https://github.com/720kb/angular-datepicker/blob/master/index.html) it works, if any problem please reopen the issue.

Thank you for reporting.
