### ISSUE TITLE
date-max-limit using new Date() object

### ISSUE THREAD

**Issue by regmish** [720kb/angular-datepicker#68]
I have the following html:

`<datepicker date-max-limit="{{currentDate}}">
    <input type="text" ng-model="dateOfBirth" />
</datepicker>`

and in my controller:
`$scope.currentDate = new Date();`

I get following error:
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: y in paginationYears, Duplicate key: number:NaN, Duplicate value: null

**Comment by sumanla13a** [comment]
I think the datepicker creates its own isolated scope so it is not able to pickup the date you set from your controller.

Try adding `$scope.current.date = new Date(); //in your controller`

and in your view
`<datepicker date-max-limit="{{current.date}}"> <input type="text" ng-model="dateOfBirth" /> </datepicker>`

It should work this way

**Comment by 45kb** [comment]
@shankar-mits  Hi, there is some problem with newDate() objects,  since the directive seems to return them with 4 double quotas: ""2015-07-02T07:36:00.830Z""

At the moment the advice is to use something like this:

```
<datepicker date-max-limit="{{currentDate.toString()}}">
 <input type="text" ng-model="dateOfBirth" /> 
</datepicker>
```

Sorry for the trouble, we will try to check deeply what's happening.

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/issues/65

**Comment by andrewboni** [comment]
Also running into this. I'm doing `$scope.maxDate = moment().format('YYYY-MM-DD')`
and then `date-max-limit="maxDate"`. Tried adding `.toString()` to no avail. Thoughts?

**Comment by 45kb** [comment]
Hi @andrewboni you don't need to toString() your date, toString() is only a dirt workaround when you are passing a new Date() object.

In your case you just have to use: `date-max-limit="{{maxDate}}"`

If still doesn't work, please paste the full datepicker HTML.

**Comment by leofachini** [comment]
HI @45kb, @andrewboni, what about we change the '@' literal scope of dateMaxLimit to '<' one-time biding scope? I tried here and seems to work fine as long as you send a valid type of date in a String. 

For example: 
`date-max-limit="'2016,3'"`

Set the dateMaxLimit to 2016/03/01.
Here is what the [angular doc's] (https://docs.angularjs.org/api/ng/service/$compile) about the scope.

Regards.

**Comment by AmitPoojary** [comment]
date-max-limit="{{currentDate | date}}" try this.

**Comment by 45kb** [comment]
moved to one global issue https://github.com/720kb/angular-datepicker/issues/227

**Comment by craigdanj** [comment]
> date-max-limit="{{currentDate | date}}" try this.

This worked for me.

**Comment by malavcygnet** [comment]
date-max-limit="{{currentDate.toString()}}" try this.

This worked
