### ISSUE TITLE
Options to make datepicker to show by default.

### ISSUE THREAD

**Issue by piyushchauhan2011** [720kb/angular-datepicker#69]
I want to know if it is possible to make the datepicker to show by default without clicking on the input box, just like options in jquery datepicker to be shown by default.

**Comment by 45kb** [comment]
Hi @piyushchauhan2011  you already can achieve this, check the last comments: https://github.com/720kb/angular-datepicker/issues/35#issuecomment-118103161

**Comment by piyushchauhan2011** [comment]
:+1:  Works perfectly. `{ position: relative; visibility: visible; }`
