### ISSUE TITLE
Customised selector not working

### ISSUE THREAD

**Issue by shankar-mits** [720kb/angular-datepicker#71]
I am having the same issue, I use foundation.css and here is my snippet
`<datepicker date-format="MMMM d, y", date-max-limit="#{currentDate}", selector = "fa-calendar"> <input type="text", name='dob' ng-model="dateOfBirth" placeholder ="Date Picker"> <i class ="fa fa-calendar"> </datepicker>`

clicking on calendar icon shows datepicker, but input field isnot filled.

**Comment by AshishTiwariMEAN** [comment]
I am having the same issue,

**Comment by AshishTiwariMEAN** [comment]
<datepicker date-format="MM/dd/yyyy" button-prev="<i class='fa fa-arrow-left'></i>" button-next="<i class='fa fa-arrow-right'></i>" data-selector="form-control">
                                                <div class="datep">
                                                    <span class="input-group-addon" style="cursor: pointer">
                                                        <i class="fa fa-lg fa-calendar"></i>
                                                    </span>
                                                    <input type="text" date='MM/dd/yyyy'  name="date_of_birth" class="form-control" placeholder="mm/dd/yyyy" required>
                                                    
                                                </div>
                                                <span class="iconmoon-right fa fa-exclamation-circle red exclamation" ng-show="patientFrm.date_of_birth.$dirty && patientFrm.date_of_birth.$invalid"></span>
                                            </datepicker>
