### ISSUE TITLE
disabling dates in datepicker

### ISSUE THREAD

**Issue by ramkumar28782** [720kb/angular-datepicker#74]
I was using datepicker by 720kb.
Could you please help me with date-disable function if available in this datepicker.
 
I could not reach a documentation for disabling weekdates using this datepicker.

**Comment by 45kb** [comment]
@ramkumar28782 Hi at the moment this is not possible, there is no date-disable attribute.

https://github.com/720kb/angular-datepicker/issues/21

**Comment by lucas-nadalutti** [comment]
Looking forward to this :)
