### ISSUE TITLE
namespace conflict when running bootstrap-ui

### ISSUE THREAD

**Issue by k2lh** [720kb/angular-datepicker#76]
In the angularjs bootstrap setup, the calendar feature is called 'datepicker'. With angular-datepicker also calling the exact same name for its directive, we're getting conflicts. When we manually edit the angular-datepicker src to change the directive name, we're still not seeing a dropdown. Looks like possibly another conflict with bootstrap-ui, this time around the dropdown toggle. If your directive doesn't play well with bootstrap-ui, might want to mention that as an anti-dependency on the readme.

**Comment by 45kb** [comment]
Hi @k2lh  take a look here https://github.com/720kb/angular-datepicker/issues/27

**Comment by tiagomsmagalhaes** [comment]
why not using a prefix?
