### ISSUE TITLE
nextMonth() with date-max-limit

### ISSUE THREAD

**Issue by jkns** [720kb/angular-datepicker#77]
When using ```date-max-limit``` with a date in the current month (e.g. today), when you click on the next month button the ```manageNextMonth()``` function will call ```$scope.resetToMaxDate();``` on the first click, but not on subsequent clicks.

This means on the first click, the days in the calendar switch to next months days but the month doesn't change. Clicking again moves to the next month.

I have removed the following from ```manageNextMonth()``` as I'm not sure what it's trying to accomplish:

```
//check if max date is ok
if (dateMaxLimit) {
    if (!$scope.isSelectableMaxDate($scope.year + '/' + $scope.monthNumber + '/' + $scope.day)) {
        $scope.resetToMaxDate();
    }
}
```

**Comment by 45kb** [comment]
Hi @jkns  try with the new version https://github.com/720kb/angular-datepicker/releases/tag/0.2.7

Seems fixed now

**Comment by jkns** [comment]
Thanks @45kb, you're a superstar. Working fine now. Great plugin.

**Comment by 45kb** [comment]
@jkns glad if it helps you in your needs, you're welcome at anytime! :+1:
