### ISSUE TITLE
Can't select previous month in mobile view when using date-min-limit

### ISSUE THREAD

**Issue by jkns** [720kb/angular-datepicker#81]
If you have ```date-min-limit``` set to a day in the previous month, you can view the previous month in the desktop view:

![screen shot 2015-09-03 at 11 01 45](https://cloud.githubusercontent.com/assets/6670657/9655774/78d3802e-522b-11e5-9127-ab96cdac3043.png)

But the previous month in the drop down in the mobile view is disabled, preventing you from viewing the month with the min date in:

![screen shot 2015-09-03 at 11 02 08](https://cloud.githubusercontent.com/assets/6670657/9655773/78cef5fe-522b-11e5-9315-0dd64487f389.png)

**Comment by 45kb** [comment]
@jkns  Hi, thank you for reporting this, yes the mobile side needs a deep check, something is not correct unfortunately, feel free to try something for this if you can, it will be a lot appreciated!

**Comment by jkns** [comment]
I had a quick look but wasn't sure if you'd know a bit more off the top of your head. I'll hopefully have a closer look this week.

**Comment by 45kb** [comment]
@jkns could you please show your html because testing i am unable to replicate the bug, actually it works correctly here...

**Comment by jkns** [comment]
Here you go @45kb - http://codepen.io/anon/pen/eppZed

I've used your dark theme example and only added ```date-min-limit="2015-08-28"```. If you view on a mobile (or using Chrome's emulator), you cannot select the previous month from the dropdown:

![screen shot 2015-09-10 at 11 30 27](https://cloud.githubusercontent.com/assets/6670657/9786200/11b2198e-57b0-11e5-91db-bc283a3b7ed6.png)

**Comment by 45kb** [comment]
@jkns the pen is not updated for long time, i guess for sure there will be bugs on it, have you tried also with latest version of datepicker ? maybe on your own html page?

**Comment by jkns** [comment]
Updated to use v0.2.10 but still having the same issue - http://codepen.io/anon/pen/meePoo

Have you got it working somewhere I can see?

From the code below it looks like the current day is getting passed to ```isSelectableMinDate()```.

```ng-disabled=\'!isSelectableMaxDate(item + " " + day + ", " + year) || !isSelectableMinDate(item + " " + day + ", " + year)\'```

So, for example, if today is 10 September and you set ```date-min-limit``` to 28 August, it's actually 10 August that gets sent to ```isSelectableMinDate()``` (not 28 August). 10 August is not selectable so it gets disabled.

**Comment by 45kb** [comment]
Ok, strange, i always test everything in the repo index.html the file i linked you above, i will double check this :)

**Comment by 45kb** [comment]
@jkns Still same problem? Can you try the latest version, actually it seems it works, let me know if you can!

Thanks a lot.

**Comment by jkns** [comment]
@45kb Thanks! I'll check and let you know.

**Comment by jkns** [comment]
@45kb Yep, fixed when testing with the latest version (0.2.24-beta). Thank you.

**Comment by 45kb** [comment]
@jkns Thanks!
