### ISSUE TITLE
Update bower angular dependency version

### ISSUE THREAD

**Issue by ttbarnes** [720kb/angular-datepicker#82]
Currently requires `1.3.1`, would be great to have a later version.

**Comment by 45kb** [comment]
Hi, If you mean the bower angular dependency for sure, needs to be updated.

Is that what you mean?

**Comment by ttbarnes** [comment]
@45kb Yes exactly, will update the title

**Comment by 45kb** [comment]
Sorry didn't noticed the title at all  :(

Done in last commit ;)
