### ISSUE TITLE
Ability to define inline layout(?)

### ISSUE THREAD

**Issue by ttbarnes** [720kb/angular-datepicker#83]
Currently the datepicker uses `position:absolute`.There could be cases (like with a project i'm on), where you want this to be inline instead.

I know you can customise the CSS, but as a suggestion, maybe it would be good to have an optional attribute to define this, maybe something like this:

`layout="inline"`

otherwise, it would be absolute.

Maybe it's a bad idea because (without customising the CSS and using it 'out of the box') there would be unused styles.  Then again, if both styles were in place it would be v.easy to switch from one layout to another, if desired with A/B testing or something.

If you think this is a good idea i'd be happy to work on a PR (time permitting).

**Comment by 45kb** [comment]
@ttbarnes  Hi, thank you for the suggestion, actually a new attribute for this is quite too much, what could be nice is to add themes, so for example you could create sticky datepickers and more, as well as inline datepicker, that way you just have to change css file, what you think about it?

**Comment by ttbarnes** [comment]
@45kb hey, you're right, that's a much better solution - lots of options for moving forwards. :+1:

**Comment by 45kb** [comment]
@ttbarnes  feel free if you want to add themes to a new directory :) thank you a lot

**Comment by 45kb** [comment]
https://github.com/720kb/angular-datepicker/issues/84
