### ISSUE TITLE
Multiple concurrent date picker elements are linked

### ISSUE THREAD

**Issue by embarg0** [720kb/angular-datepicker#85]
Having two datepicker elements on the same view does not appear to be possible -- making a change (user selects a date, adding date-set attribute) to one makes the same change in the other.

**Comment by jkns** [comment]
I have multiple date pickers on the same view & they work fine. Can you post code?

**Comment by embarg0** [comment]
Oh you are right -- I got it working -- I had the same ngModel variable for both and that was obviously duplicating the user choice, but also the date-set on the parent element for both the instances of the datepicker. Closing the issue, cheers!

**Comment by jkns** [comment]
Ha! Easy mistake. Glad you got it working.
