### ISSUE TITLE
Option to show datepicker by default

### ISSUE THREAD

**Issue by EdmundMai** [720kb/angular-datepicker#88]
It would be nice to add an attribute to the directive to show the datepicker by default. Could default to false, but if set to true `$scope.showCalendar()` would be called

**Comment by 45kb** [comment]
@EdmundMai  Hi yes we all agree :)

We will try to make this but PRs are always appreciated! Feel free to try something if you can :+1:

**Comment by wouldgo** [comment]
Close due the #89 merged PR.
Thanks to @goggenb.
