### ISSUE TITLE
Possibilty to change days string

### ISSUE THREAD

**Issue by brunocascio** [720kb/angular-datepicker#90]
Hi guys,

I need to change the names of days.

How i do this?

For example

`MON TUE WED THU FRI SAT SUN` => `MO TU WE TH FR SA SU`

Thanks!

**Comment by 45kb** [comment]
Hi @brunocascio as you can see here : https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L587

The code is returning the days filtered via angular date $filter, you should be able to change this function or alter the code to your needs.

If you then wants to help and PR a new customizable option to achieve this we'll be much glad!

**Comment by brunocascio** [comment]
Ok, thanks!

**Comment by 45kb** [comment]
@brunocascio  You're welcome :+1:
