### ISSUE TITLE
Datepicker input not work with different hierarchy

### ISSUE THREAD

**Issue by brunocascio** [720kb/angular-datepicker#91]
This code doesn't work. I can select date but the value is not updated.

```
<datepicker button-prev="<" button-next=">" date-format="MM / dd / yyyy">
	<div class="ui right labeled input">
		<input class="input-light" type="text" ng-model="customer.organization.organization.einCertificationDate" placeholder="Select a Date">
			<div class="ui label">
				<i class="nyb-icon-calendar"></i>
			</div>
	</div>
</datepicker>
```

If change code to: (only test DOM), works.
```
<datepicker button-prev="<" button-next=">" date-format="MM / dd / yyyy">
    <input class="input-light" type="text" ng-model="customer.organization.organization.einCertificationDate" placeholder="Select a Date">
	<div class="ui right labeled input">
			<div class="ui label">
				<i class="nyb-icon-calendar"></i>
			</div>
	</div>
</datepicker>
```

I think the problem is related to this part of [code.](https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L144)

**Comment by wouldgo** [comment]
Hi @brunocascio,

I think you're right about the problem. We are doing an analysis due we suppose this issue is related to #94 .

If you have ideas let us know.

**Comment by 45kb** [comment]
Hi @brunocascio , did you tried ```<datepicker selector="my-input-class">``` ?

Let know if you can, please, thank you.

**Comment by brunocascio** [comment]
Sorry, but i changed the plugin for other requirements. I cannot test right now :/

Thanks!

**Comment by 45kb** [comment]
Thank you ok, i close the issue but you'll still be able to reply in here.

**Comment by AshishTiwariMEAN** [comment]
when we change selector the input filed not filled properly.
Please provide solution for this.
