### ISSUE TITLE
Retrieving date in popup with ngmodel

### ISSUE THREAD

**Issue by spaeth21** [720kb/angular-datepicker#92]
When I pull data from a database into ngmodel and then open the datepicker it still defaults to whatever todays current date is instead of going directly to the date retrieved into ngmodel. If I pick a different date in the datepicker and reopen it, it of course registers the new date, probably from what is saved in its scope. Is there a way of forcing the datepicker to see if the ngmodel has a current date and then go directly to that date?

**Comment by wouldgo** [comment]
Hi @spaeth21,
have you tried to use the attribute presented [here](https://github.com/720kb/angular-datepicker#default-date)?

Hope helps you.

**Comment by spaeth21** [comment]
Perfect thank you, I am now just using date-set="{{modelName}}" and it works. Sorry for not reading all the documents, but thanks.
