### ISSUE TITLE
Use Esc button to close datepicker.

### ISSUE THREAD

**Issue by padmkris123** [720kb/angular-datepicker#93]
Hi,

Is there a way to hide the calendar when the user presses the Esc button?  

Thanks in advance,
Padma

**Comment by wouldgo** [comment]
Hi again @padmkris123,

at the moment there is no keyboard binding out of the directive box.
If you have ideas or proposal to achieve this please write down your thoughts.

Best regards,
Dario

**Comment by 45kb** [comment]
hi, i am going to close  the issue, we can then discuss it but imho keyboard bindings could be done outside of the directive, don't you agree?

For exaple you could bind Esc button to the input blur and the datepicker will hide
