### ISSUE TITLE
Calendar on blur for Input as grandchild

### ISSUE THREAD

**Issue by padmkris123** [720kb/angular-datepicker#94]
Hi, 

I have used datepicker the way it is described in 'Input as grandchild' section. I notice that the Calendar does not close on blur/focusout. Can somebody help?

Also, a suggestion for the example code snippet provided in README document. It should be the following with matching css class names for selector attribute in datepicker tag and class attribute in the grandchild element.
```javascript
 <datepicker date-format="yyyy-MM-dd" selector="form-control">
    <div class="input-group">
        <input placeholder="Choose a date"/>
        <span class="input-group-addon" style="cursor: pointer"><i class="form-control fa-calendar"></i></span>
    </div>
</datepicker>
```

**Comment by 45kb** [comment]
Hi have you tried this instead?

 ```html
    <div datepicker date-format="yyyy-MM-dd" selector="form-control" class="input-group">
        <input placeholder="Choose a date"/>
        <span class="input-group-addon" style="cursor: pointer"><i class="form-control fa-calendar"></i>  </span>
    </div>
```

Still not working?
