### ISSUE TITLE
Missing month on mobile

### ISSUE THREAD

**Issue by tarikdedic** [720kb/angular-datepicker#95]
There is no 'January' on mobile devices. I didn't used any special options, just included javascript file.

![screenshot_2015-10-01-09-30-22](https://cloud.githubusercontent.com/assets/3251107/10215127/52f4d286-681f-11e5-8798-df5f7caf65f2.png)

**Comment by wouldgo** [comment]
Hi @tarikdedic,

could you please paste the html that produce the datepicker?
Thanks,

Dario

**Comment by tarikdedic** [comment]
@wouldgo 
Here it is...

<div class="input-group">
   <span class="input-group-addon"><span class='icon-calendar-o'></span></span>
   <datepicker date-format="dd-MM-yyyy">
      <input class="form-control" id="rbirthday" type="text" 
         placeholder="{{::__('register_user$lbl_register_birthday', 'Birthday')}}" ng-model="msBirthdate"                           name="date" required>
   </datepicker>
</div>

**Comment by tarikdedic** [comment]
@wouldgo 
I also replaced my old version with the newest one..
- Angular Datepicker v0.2.4
+ Angular Datepicker v0.2.10

Still the same problem...

**Comment by 45kb** [comment]
Hi @tarikdedic  i tested using the same code (you can try it from [here](https://github.com/720kb/angular-datepicker/blob/master/index.html))

I attach both mobile and safari (iOS) screenshots, looks like the problem does not exist, the best way could be if you create a jsfiddle or plunkr to show live what is happening.

![screenshot_2015-10-07-09-53-49](https://cloud.githubusercontent.com/assets/7761650/10332085/11c8c43c-6cdb-11e5-9287-c165998f7cd4.png)
![schermata 2015-10-07 alle 09 54 22](https://cloud.githubusercontent.com/assets/7761650/10332106/22657fe2-6cdb-11e5-980b-9bad82d46500.png)

**Comment by tarikdedic** [comment]
Blame this issue on me... Sorry.

But now I have another issue with i18n. I included angular i18n file (angular-locale_hr.js) and when the month is changed, days disappeared..
This is only occurring on mobile devices..

![issue1](https://cloud.githubusercontent.com/assets/3251107/10429729/f6f70f6e-70fa-11e5-8f1d-9e39465169e8.png)

**Comment by halibegic** [comment]
Hi,

Problem from the last comment was in "selectedMonthHandle" function because parameter "selectedMonth" in this case is "sječanj" and than $scope.monthNumber is created like new Date('01 siječanj 2000') which results in NaN.

**Comment by 45kb** [comment]
This bug looks fixed now, if you still having problem please let know.

thank you all guys :+1:
