### ISSUE TITLE
DOM placement

### ISSUE THREAD

**Issue by bnhovde** [720kb/angular-datepicker#97]
Hi,

Is there any way to modify where in the DOM the datepicker div is output?

In my case, where my input field is in a container that's 50% of the screen width it's quite hard to position the datepicker correctly. Especially on mobile. See screenshot for example.

The solution here would be to be able to have the datepicker div appear just before the closing <datepicker/> tag. I could position the container with position fixed, but this comes with several downsides.

![Image of Yaktocat](https://photos-1.dropbox.com/t/2/AAA37_GuzljHFkrbIVQV4id8EAb6NA-MbJ7nJrlhqgAbqg/12/421431012/png/32x32/1/1444406400/0/2/Screenshot%202015-10-09%2015.26.49.png/COSN-sgBIAEgAiADIAYgBygC/CtPo8z-rT8FMPQ70_dNw1gbc3MBf5vtXVXrsYdS_ofA?size=2048x1536&size_mode=2)

**Comment by 45kb** [comment]
@bnhovde  hi, the current implementation makes datepicker to follow the input size.

I don't quite understand what you mean for "closing tag" ?

My suggestion, till we release a complete new verison of the datepicker, is to edit the css file.

**Comment by bnhovde** [comment]
@45kb Thanks for your reply, and for this directive in general. I wasn't aware there was a new version in the making.

You're right, css should solve it for now. In my case my form "columns" had to be positioned relative for icon placement, but I'll find a way around this.

Just to illustrate the issue i knocked up this quick codepen: http://codepen.io/bnhovde/pen/jbLWqY?editors=110

Thanks again!
B
