### ISSUE TITLE
Multiple Directive Resource Contention

### ISSUE THREAD

**Issue by rawoke083** [720kb/angular-datepicker#98]
HI I'm using the very basic

    <datepicker>
      <input ng-model="date" type="text"/>
    </datepicker>

Using AngularJS v1.4.0

Only thing funny is that I'm using "ControllerAs syntax"

Error: $compile:multidir
Multiple Directive Resource Contention
Multiple directives [datepickerdatepicker, new/isolated scope
] asking for {4} on: {5}

**Comment by 45kb** [comment]
@rawoke083  Hi, are you using multiple ```datepicker``` directives such as bootstra-ui datepicker?

**Comment by 45kb** [comment]
Going to close, please re-open the issue whenever you need.

**Comment by fabiowitt** [comment]
I'm having this issue and I'm using bootstrap-ui. What is the approach on this matter?

**Comment by 45kb** [comment]
Hi, so should work using

```<div class="datepicker">``` instead of ```<datepicker>```

Anyway including multiple directives for the same tool (in this case a datepicker) is really not a good practice.

Just remove the bootstrap-ui datepicker if you want to use another :+1:

**Comment by fabiowitt** [comment]
I see. Thanks a bunch :+1: !

**Comment by mayankkalbhor** [comment]
Thanks 45kb

**Comment by 45kb** [comment]
@mayankkalbhor you're welcome
